import type { CardData } from "@repo/cards-domain";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const CLASSICAL_CARDS: CardData[] = [
  {
    catalogNumber: 2,
    id: 38,
    tracksOut: [39],
    title: "God Save the King",
    year: "1745",
    genre: "Anthem",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 5,
    rarity: "Banger",
    artwork: `${ART}artwork.god-save-the-king-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.god-save-the-king-v1.png"],
    ...(artworkPromptFor(38) ?? {}),
  },
  {
    catalogNumber: 3,
    id: 39,
    tracksOut: [38, 29],
    title: "God Save the Queen",
    year: "1745",
    genre: "Anthem",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 5,
    rarity: "Banger",
    artwork: `${ART}artwork.god-save-the-queen-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.god-save-the-queen-v1.png"],
    ...(artworkPromptFor(39) ?? {}),
  },
  {
    catalogNumber: 4,
    id: 54,
    tracksOut: [55],
    title: "Spring (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: "1725",
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-spring-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-spring-v1.png"],
    ...(artworkPromptFor(54) ?? {}),
  },
  {
    catalogNumber: 5,
    id: 55,
    tracksOut: [56],
    title: "Summer (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: "1725",
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-summer-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-summer-v1.png"],
    ...(artworkPromptFor(55) ?? {}),
  },
  {
    catalogNumber: 6,
    id: 56,
    tracksOut: [57],
    title: "Autumn (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: "1725",
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-autumn-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-autumn-v1.png"],
    ...(artworkPromptFor(56) ?? {}),
  },
  {
    catalogNumber: 7,
    id: 57,
    tracksOut: [54],
    title: "Winter (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: "1725",
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-winter-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-winter-v1.png"],
    ...(artworkPromptFor(57) ?? {}),
  },
  {
    catalogNumber: 8,
    id: 65,
    title: "Lacrimosa",
    artist: "Wolfgang Amadeus Mozart",
    year: "1791",
    genre: "Sacred Choral",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.mozart-requiem-lacrimosa-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.mozart-requiem-lacrimosa-v1.png"],
  },
  {
    catalogNumber: 9,
    id: 66,
    title: "Dies Irae",
    artist: "Giuseppe Verdi",
    year: "1874",
    genre: "Romantic Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.verdi-dies-irae-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.verdi-dies-irae-v1.png"],
    ...(artworkPromptFor(66) ?? {}),
  },
  {
    catalogNumber: 10,
    id: 72,
    tracksOut: [116],
    title: "Symphony No. 5",
    artist: "Ludwig van Beethoven",
    year: "1808",
    genre: "Symphonic Showpiece",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.beethoven-symphony-no-5-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.beethoven-symphony-no-5-v1.png"],
    ...(artworkPromptFor(72) ?? {}),
    artworkOffsetY: -25,
  },
  {
    catalogNumber: 11,
    id: 73,
    title: "O Fortuna",
    artist: "Carl Orff",
    year: "1937",
    genre: "Symphonic Showpiece",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.carmina-burana-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.carmina-burana-v1.png"],
  },
  {
    catalogNumber: 12,
    id: 7,
    title: "Ride of the Valkyries",
    artist: "Richard Wagner",
    year: "1876",
    genre: "Opera",
    ability: "Fortissimo",
    abilityDesc: "Deals damage in three separate strikes of 60% power each.",
    pop: 6,
    rarity: "Legendary",
    artwork: `${ART}artwork.wagner-ride-of-the-valkyries-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.wagner-ride-of-the-valkyries-v1.png"],
    ...(artworkPromptFor(7) ?? {}),
  },
] as CardData[];
