import type { CardData } from "@repo/cards-domain";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const ROCK_CARDS: CardData[] = [
  {
    catalogNumber: 1,
    id: 1,
    title: "Bohemian Rhapsody",
    year: "1975",
    genre: "Opera Rock",
    ability: "Anthemic",
    abilityDesc: "Doubles momentum on any track with a guitar solo.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.bohemian-rhapsody-v2.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.bohemian-rhapsody-v2.png"],
  },
  {
    catalogNumber: 3,
    id: 28,
    artworkOffsetY: -25,
    title: "All You Need Is Love",
    year: "1968",
    genre: "Opera Rock",
    ability: "Coda",
    abilityDesc: "Draws a second card if popularity is 9.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.beatles-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.beatles-v1.png"],
  },
  {
    catalogNumber: 4,
    id: 29,
    title: "God Save the Queen",
    year: "1977",
    genre: "Punk",
    ability: "Anarchy",
    abilityDesc:
      "Opponent loses 10 popularity when you play a second Rock card this round.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.the-sex-pistols-god-save-the-queen-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.the-sex-pistols-god-save-the-queen-v1.png"],
  },
  {
    catalogNumber: 5,
    id: 51,
    title: "Stairway to Heaven",
    year: "1971",
    genre: "Prog Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.led-zeppelin-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.led-zeppelin-v1.png"],
    ...(artworkPromptFor(51) ?? {}),
  },
  {
    id: 63,
    catalogNumber: 6,
    title: "Suck My Kiss",
    year: "1991",
    genre: "Pop Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.red-hot-chili-peppers-suck-my-kiss-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.red-hot-chili-peppers-suck-my-kiss-v1.png"],
    ...(artworkPromptFor(63) ?? {}),
  },
  {
    catalogNumber: 7,
    id: 68,
    title: "Seven Nation Army",
    year: "2003",
    genre: "Alternative Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.white-stripes-seven-nation-army-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.white-stripes-seven-nation-army-v1.png"],
    ...(artworkPromptFor(68) ?? {}),
  },
  {
    catalogNumber: 8,
    id: 71,
    title: "Enter Sandman",
    year: "1991",
    genre: "Metal",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.metallica-enter-sandman-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.metallica-enter-sandman-v1.png"],
    ...(artworkPromptFor(71) ?? {}),
  },
  {
    catalogNumber: 9,
    id: 74,
    title: "Smells Like Teen Spirit",
    year: "1991",
    genre: "Grunge",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.smells-like-teen-spirit-v2.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.smells-like-teen-spirit-v2.png"],
  },
  {
    catalogNumber: 10,
    id: 75,
    title: "Money",
    year: "1973",
    genre: "Prog Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.money-v2.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.money-v2.png"],
  },
  {
    catalogNumber: 11,
    id: 80,
    title: "Guerrilla Radio",
    year: "1999",
    genre: "Pop Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    artworkOffsetY: -24,
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.ratm-guerilla-radio-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.ratm-guerilla-radio-v1.png"],
    ...(artworkPromptFor(80) ?? {}),
  },
  {
    catalogNumber: 12,
    id: 83,
    title: "Woman to Woman",
    year: "1972",
    genre: "Soul Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    artworkOffsetY: -35,
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.joe-cocker-woman-to-woman-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.joe-cocker-woman-to-woman-v1.png"],
  },
  {
    catalogNumber: 13,
    id: 87,
    title: "Africa",
    year: "1982",
    genre: "Pop Rock",
    ability: "Savanna stack",
    abilityDesc:
      "Reads as pop on the strip but smuggles hardcore weight: massed percussion, marimba layers, and session-musician polyphony under an immovable chorus.",
    pop: 9,
    rarity: "Classic",
    artwork: `${ART}artwork.toto-africa-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.toto-africa-v1.png"],
    artworkOffsetY: -30,
    ...(artworkPromptFor(87) ?? {}),
  },
  {
    catalogNumber: 14,
    id: 92,
    title: "Superstition",
    year: "1972",
    genre: "Hard Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.jeff-beck-superstition-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.jeff-beck-superstition-v1.png"],
    ...(artworkPromptFor(92) ?? {}),
  },
  {
    catalogNumber: 16,
    id: 102,
    title: "In the End",
    year: "2000",
    genre: "Pop Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    artworkOffsetY: -20,
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.linkin-park-in-the-end-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.linkin-park-in-the-end-v1.png"],
  },
  {
    catalogNumber: 17,
    id: 105,
    title: "I Shot the Sheriff",
    year: "1974",
    genre: "Blues Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.eric-clapton-i-shot-the-sherif-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.eric-clapton-i-shot-the-sherif-v1.png"],
    ...(artworkPromptFor(105) ?? {}),
  },
  {
    catalogNumber: 18,
    id: 106,
    title: "Vitamin C",
    year: "1972",
    genre: "Krautrock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    songsOut: [107],
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.can-vitamine-c-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.can-vitamine-c-v1.png"],
    artworkOffsetY: -25,
    ...(artworkPromptFor(106) ?? {}),
  },
  {
    catalogNumber: 19,
    id: 110,
    title: "Mad World",
    year: "2001",
    genre: "Chamber Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.gary-jules-mad-world-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.gary-jules-mad-world-v1.png"],
    ...(artworkPromptFor(110) ?? {}),
  },
] as CardData[];
