import type { WishlistCardDef } from "@repo/cards-domain";

export type { WishlistCardDef } from "@repo/cards-domain";

const P = "Wishlist catalogue entry.";
const A = "Reserve";

/** IDs 12xxx avoid collision with shipped deck (1–33, 9101). */
export const WISHLIST_CARD_DEFS: WishlistCardDef[] = [
  {
    id: 12006,
    title: "Sous les sunlights des tropiques",
    artist: "Gilbert Montagné",
    year: "1984",
    kind: "Wishlist",
    genre: "Disco",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12010,
    title: "Jolene",
    artist: "Dolly Parton",
    year: "1973",
    kind: "Wishlist",
    genre: "Disco Pop",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12011,
    title: "Rapper's Delight",
    artist: "The Sugarhill Gang",
    year: "1979",
    kind: "Wishlist",
    genre: "Rap",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12012,
    title: "Highway to Hell",
    artist: "AC/DC",
    year: "1979",
    kind: "Wishlist",
    genre: "Hard Rock",
    rarity: "LEGENDARY",
    pop: 9,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12013,
    title: "Thunderstruck",
    artist: "AC/DC",
    year: "1990",
    kind: "Wishlist",
    genre: "Hard Rock",
    rarity: "CLASSIC",
    pop: 9,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12014,
    title: "Hell's Bells",
    artist: "AC/DC",
    year: "1980",
    kind: "Wishlist",
    genre: "Hard Rock",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12016,
    title: "You'll Never Walk Alone",
    artist: "Gerry and the Pacemakers",
    year: "1963",
    kind: "Wishlist",
    genre: "Early Pop Rock",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12017,
    title: "Sweet Caroline",
    artist: "Neil Diamond",
    year: "1969",
    kind: "Wishlist",
    genre: "Disco Pop",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12018,
    title: "Baby Shark",
    artist: "Pinkfong",
    year: "2016",
    kind: "Wishlist",
    genre: "Electropop",
    rarity: "BANGER",
    pop: 9,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12019,
    title: "Blinding Lights",
    artist: "The Weeknd",
    year: "2019",
    kind: "Wishlist",
    genre: "Electropop",
    rarity: "LEGENDARY",
    pop: 9,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12020,
    title: "Superstition",
    artist: "Stevie Wonder",
    year: "1972",
    kind: "Wishlist",
    genre: "Disco",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12021,
    title: "Walk This Way",
    artist: "Aerosmith",
    year: "1975",
    kind: "Wishlist",
    genre: "Pop Rock",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12022,
    title: "Walk This Way",
    artist: "Run-DMC feat. Aerosmith",
    year: "1986",
    kind: "Wishlist",
    genre: "Rap",
    rarity: "LEGENDARY",
    pop: 9,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12025,
    title: "The Pretender",
    artist: "Foo Fighters",
    year: "2007",
    kind: "Wishlist",
    genre: "Post Grunge",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12026,
    title: "The Great Pretender",
    artist: "The Platters",
    year: "1955",
    kind: "Wishlist",
    genre: "Soul",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12027,
    title: "The Great Pretender",
    artist: "Frank Sinatra",
    year: "1958",
    kind: "Wishlist",
    genre: "Soul",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12028,
    title: "Chargé",
    artist: "Triangle des Bermudes",
    year: "2020",
    kind: "Wishlist",
    genre: "Rap",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12030,
    title: "My Way",
    artist: "Frank Sinatra",
    year: "1969",
    kind: "Wishlist",
    genre: "Soul",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12031,
    title: "My Way",
    artist: "Sid Vicious",
    year: "1978",
    kind: "Wishlist",
    genre: "Punk",
    rarity: "CLASSIC",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12032,
    title: "La Mer",
    artist: "Charles Trenet",
    year: "1946",
    kind: "Card",
    country: "France",
    genre: "French Variety",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12033,
    title: "Beyond the Sea",
    artist: "Bobby Darin",
    year: "1960",
    kind: "Wishlist",
    genre: "Traditional Pop",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12034,
    title: "Hallelujah",
    artist: "Leonard Cohen",
    year: "1984",
    kind: "Wishlist",
    genre: "Pop Rock",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12035,
    title: "Hallelujah",
    artist: "Jeff Buckley",
    year: "1994",
    kind: "Wishlist",
    genre: "Pop Rock",
    rarity: "LEGENDARY",
    pop: 9,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12047,
    title: "Take Five",
    artist: "The Dave Brubeck Quartet",
    year: "1959",
    kind: "Wishlist",
    genre: "Jazz",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12048,
    title: "Mission: Impossible",
    artist: "Lalo Schifrin",
    year: "1966",
    kind: "Wishlist",
    genre: "Symphonic Showpiece",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12062,
    title: "The Entertainer",
    artist: "Scott Joplin",
    year: "1902",
    kind: "Wishlist",
    genre: "Ragtime",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12063,
    title: "Maple Leaf Rag",
    artist: "Scott Joplin",
    year: "1899",
    kind: "Wishlist",
    genre: "Ragtime",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12064,
    title: "Clair de Lune",
    artist: "Claude Debussy",
    year: "1905",
    kind: "Wishlist",
    genre: "Impressionist Classical",
    rarity: "CLASSIC",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12065,
    title: "Gymnopédie No. 1",
    artist: "Erik Satie",
    year: "1888",
    kind: "Wishlist",
    genre: "Impressionist Classical",
    rarity: "CLASSIC",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12066,
    title: "Für Elise",
    artist: "Ludwig van Beethoven",
    year: "1810",
    kind: "Wishlist",
    genre: "Romantic Classical",
    rarity: "BANGER",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12067,
    title: "Moonlight Sonata",
    artist: "Ludwig van Beethoven",
    year: "1801",
    kind: "Wishlist",
    genre: "Romantic Classical",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12068,
    title: "La Campanella",
    artist: "Franz Liszt",
    year: "1851",
    kind: "Wishlist",
    genre: "Virtuoso Piano",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12069,
    title: "Air on the G String",
    artist: "J.S. Bach",
    year: "1871",
    kind: "Wishlist",
    genre: "Baroque Classical",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12070,
    title: "Hungarian Dance No. 5",
    artist: "Johannes Brahms",
    year: "1869",
    kind: "Wishlist",
    genre: "Romantic Classical",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12071,
    title: "In the Hall of the Mountain King",
    artist: "Edvard Grieg",
    year: "1875",
    kind: "Wishlist",
    genre: "Symphonic Showpiece",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12072,
    title: "Canon in D",
    artist: "Johann Pachelbel",
    year: "1680",
    kind: "Wishlist",
    genre: "Baroque Classical",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12073,
    title: "Nocturne Op. 9 No. 2",
    artist: "Frédéric Chopin",
    year: "1832",
    kind: "Wishlist",
    genre: "Romantic Classical",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12074,
    title: "Swan Lake Theme",
    artist: "Pyotr Ilyich Tchaikovsky",
    year: "1876",
    kind: "Wishlist",
    genre: "Ballet",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12075,
    title: "The Blue Danube",
    artist: "Johann Strauss II",
    year: "1866",
    kind: "Wishlist",
    genre: "Waltz",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12076,
    title: "Boléro",
    artist: "Maurice Ravel",
    year: "1928",
    kind: "Wishlist",
    genre: "Symphonic Showpiece",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12077,
    title: "Carmen Overture",
    artist: "Georges Bizet",
    year: "1875",
    kind: "Wishlist",
    genre: "Opera",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12078,
    title: "Greensleeves",
    artist: "Traditional (England)",
    year: "1580",
    kind: "Card",
    country: "England",
    genre: "English Folk",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12079,
    title: "Silent Night",
    artist: "Franz Xaver Gruber",
    year: "1818",
    kind: "Wishlist",
    genre: "Christian Hymn",
    rarity: "BANGER",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12080,
    title: "When the Saints Go Marching In",
    artist: "Traditional",
    year: "1896",
    kind: "Card",
    country: "USA",
    genre: "Spiritual",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12081,
    title: "Frère Jacques",
    artist: "Traditional (France)",
    year: "1780",
    kind: "Card",
    country: "France",
    genre: "French Folk",
    rarity: "BANGER",
    pop: 6,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12082,
    title: "Londonderry Air (Danny Boy)",
    artist: "Traditional (Ireland)",
    year: "1855",
    kind: "Wishlist",
    genre: "Folk Ballad",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12083,
    title: "O Sole Mio",
    artist: "Eduardo di Capua",
    year: "1898",
    kind: "Card",
    country: "Italy",
    genre: "Neapolitan Song",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12084,
    title: "The Sorcerer's Apprentice",
    artist: "Paul Dukas",
    year: "1897",
    kind: "Wishlist",
    genre: "Symphonic Showpiece",
    rarity: "LEGENDARY",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12085,
    title: "Pomp and Circumstance",
    artist: "Edward Elgar",
    year: "1901",
    kind: "Wishlist",
    genre: "March",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12086,
    title: "The Stars and Stripes Forever",
    artist: "John Philip Sousa",
    year: "1896",
    kind: "Wishlist",
    genre: "March",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12087,
    title: "Ave Maria",
    artist: "Franz Schubert",
    year: "1825",
    kind: "Wishlist",
    genre: "Sacred Choral",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12088,
    title: "William Tell Overture",
    artist: "Gioachino Rossini",
    year: "1829",
    kind: "Wishlist",
    genre: "Opera",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12089,
    title: "Toccata and Fugue in D minor",
    artist: "J.S. Bach",
    year: "1707",
    kind: "Wishlist",
    genre: "Baroque Classical",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12090,
    title: "Eine kleine Nachtmusik",
    artist: "Wolfgang Amadeus Mozart",
    year: "1787",
    kind: "Wishlist",
    genre: "Serenade",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12091,
    title: "Ode to Joy",
    artist: "Ludwig van Beethoven",
    year: "1824",
    kind: "Wishlist",
    genre: "Symphonic Showpiece",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12092,
    title: "Oh! Susanna",
    artist: "Stephen Foster",
    year: "1848",
    kind: "Card",
    country: "USA",
    genre: "American Folk",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12093,
    title: "Yankee Doodle",
    artist: "Traditional (USA)",
    year: "1755",
    kind: "Card",
    country: "USA",
    genre: "American Folk",
    rarity: "BANGER",
    pop: 6,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12094,
    title: "Aura Lee",
    artist: "George R. Poulton",
    year: "1861",
    kind: "Wishlist",
    genre: "Folk Ballad",
    rarity: "NICHE",
    pop: 6,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12095,
    title: "House of the Rising Sun",
    artist: "Traditional",
    year: "1895",
    kind: "Wishlist",
    genre: "Folk Ballad",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12096,
    title: "Scarborough Fair",
    artist: "Traditional (England)",
    year: "1650",
    kind: "Wishlist",
    genre: "Folk Ballad",
    rarity: "CLASSIC",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12098,
    title: "Sakura Sakura",
    artist: "Traditional (Japan)",
    year: "1888",
    kind: "Card",
    country: "Japan",
    genre: "Japanese Folk",
    rarity: "BANGER",
    pop: 6,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12099,
    title: "Habanera (Carmen)",
    artist: "Georges Bizet",
    year: "1875",
    kind: "Wishlist",
    genre: "Opera",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12100,
    title: "Turkish March",
    artist: "Wolfgang Amadeus Mozart",
    year: "1783",
    kind: "Wishlist",
    genre: "Serenade",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12101,
    title: "Waltz of the Flowers",
    artist: "Pyotr Ilyich Tchaikovsky",
    year: "1892",
    kind: "Wishlist",
    genre: "Ballet",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12102,
    title: "Radetzky March",
    artist: "Johann Strauss I",
    year: "1848",
    kind: "Wishlist",
    genre: "March",
    rarity: "CLASSIC",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12103,
    title: "Toreador Song",
    artist: "Georges Bizet",
    year: "1875",
    kind: "Wishlist",
    genre: "Opera",
    rarity: "CLASSIC",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12104,
    title: "Bridal Chorus",
    artist: "Richard Wagner",
    year: "1850",
    kind: "Wishlist",
    genre: "Opera",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12105,
    title: "Ave Verum Corpus",
    artist: "Wolfgang Amadeus Mozart",
    year: "1791",
    kind: "Wishlist",
    genre: "Sacred Choral",
    rarity: "CLASSIC",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12106,
    title: "Jesu, Joy of Man's Desiring",
    artist: "J.S. Bach",
    year: "1723",
    kind: "Wishlist",
    genre: "Sacred Choral",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12107,
    title: "La Donna è Mobile",
    artist: "Giuseppe Verdi",
    year: "1851",
    kind: "Wishlist",
    genre: "Opera",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12108,
    title: "Funiculì Funiculà",
    artist: "Luigi Denza",
    year: "1880",
    kind: "Card",
    country: "Italy",
    genre: "Neapolitan Song",
    rarity: "CLASSIC",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12109,
    title: "American Idiot",
    artist: "Green Day",
    year: "2004",
    kind: "Wishlist",
    genre: "Punk",
    rarity: "LEGENDARY",
    pop: 9,
    ability: "USA Counter",
    abilityDesc:
      "When your opponent's card is a USA country (World) card, battle treats this card as countering theirs for advantage modifiers.",
  },
  {
    id: 12110,
    title: "The Metal",
    artist: "Tenacious D",
    year: "2006",
    kind: "Wishlist",
    genre: "Metal",
    rarity: "LEGENDARY",
    pop: 8,
    ability: "Four-Genre Counter",
    abilityDesc:
      "When your opponent's card is Punk Rock, Techno, Grunge, or New Wave, battle treats this card as countering theirs for advantage modifiers.",
  },
  {
    id: 12111,
    title: "La Colegiala",
    artist: "Los Ilusionistas",
    year: "1977",
    kind: "Card",
    country: "Peru",
    genre: "Peruvian Cumbia",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
    artworkPrompt:
      "Magic-style illustration, vertical 2:3, upper 40% focus. Amazon-Andean cumbia energy: electric guitar silhouette, timbales and congas as abstract shapes, warm festival crowd as anonymous silhouettes — no facial detail, no likeness to any real person. Red-and-cream palette echoing Peruvian stripes, golden late sun, dust in the air. Lower 60% simple jungle edge and stage haze. No text, no borders.",
  },
  {
    id: 12112,
    title: "Gotta Learn",
    artist: "Biga Ranx",
    year: "2012",
    kind: "Wishlist",
    genre: "Roots",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12113,
    title: "Everybody's Gotta Learn Sometime",
    artist: "The Korgis",
    year: "1980",
    kind: "Wishlist",
    genre: "New Wave",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12114,
    title: "Sorry Seems to Be the Hardest Word",
    artist: "Elton John",
    year: "1976",
    kind: "Wishlist",
    genre: "Pop Rock",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12115,
    title: "Robot Rock",
    artist: "Daft Punk",
    year: "2005",
    kind: "Wishlist",
    genre: "French House",
    rarity: "LEGENDARY",
    pop: 9,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12116,
    title: "The Payback",
    artist: "James Brown",
    year: "1973",
    kind: "Wishlist",
    genre: "Funk Soul",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12117,
    title: "Break Loose",
    artist: "Gramatik",
    year: "2013",
    kind: "Wishlist",
    genre: "Electropop",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12118,
    title: "Never Gonna Give You Up",
    artist: "Rick Astley",
    year: "2013",
    kind: "Wishlist",
    genre: "Electropop",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12119,
    title: "Sing, Sing, Sing",
    artist: "Benny Goodman",
    year: "1936",
    kind: "Wishlist",
    genre: "Jazz",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12120,
    title: "In the Mood",
    artist: "Glenn Miller",
    year: "1939",
    kind: "Wishlist",
    genre: "Jazz",
    rarity: "LEGENDARY",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12121,
    title: "Take On Me",
    artist: "a-ha",
    year: "1985",
    kind: "Wishlist",
    genre: "Synth-pop",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12122,
    title: "September",
    artist: "Earth, Wind & Fire",
    year: "1978",
    kind: "Wishlist",
    genre: "Disco",
    rarity: "LEGENDARY",
    pop: 9,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12123,
    title: "Stayin' Alive",
    artist: "Bee Gees",
    year: "1977",
    kind: "Wishlist",
    genre: "Disco",
    rarity: "LEGENDARY",
    pop: 9,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12124,
    title: "Boogie Wonderland",
    artist: "Earth, Wind & Fire",
    year: "1979",
    kind: "Wishlist",
    genre: "Disco",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12125,
    title: "I Will Survive",
    artist: "Gloria Gaynor",
    year: "1978",
    kind: "Wishlist",
    genre: "Disco",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12126,
    title: "Y.M.C.A.",
    artist: "Village People",
    year: "1978",
    kind: "Wishlist",
    genre: "Disco",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12127,
    title: "Stayin' Alive",
    artist: "N-Trance",
    year: "2003",
    kind: "Wishlist",
    genre: "Eurodance",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12128,
    title: "Rasputin",
    artist: "Boney M.",
    year: "1978",
    kind: "Wishlist",
    genre: "Disco",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12129,
    title: "Daddy Cool",
    artist: "Boney M.",
    year: "1976",
    kind: "Wishlist",
    genre: "Disco",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12130,
    title: "Barbie Girl",
    artist: "Aqua",
    year: "1997",
    kind: "Wishlist",
    genre: "Eurodance",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12131,
    title: "Dragostea Din Tei",
    artist: "O-Zone",
    year: "2003",
    kind: "Wishlist",
    genre: "Eurodance",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12132,
    title: "Around the World",
    artist: "Daft Punk",
    year: "1997",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12133,
    title: "Technologic",
    artist: "Daft Punk",
    year: "2005",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12134,
    title: "Digital Love",
    artist: "Daft Punk",
    year: "2001",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12135,
    title: "Get Lucky",
    artist: "Daft Punk",
    year: "2013",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "LEGENDARY",
    pop: 9,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12136,
    title: "Lose Yourself to Dance",
    artist: "Daft Punk",
    year: "2013",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12137,
    title: "Instant Crush",
    artist: "Daft Punk",
    year: "2013",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12138,
    title: "Derezzed",
    artist: "Daft Punk",
    year: "2010",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "NICHE",
    pop: 6,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12139,
    title: "TRON: Legacy (End Titles)",
    artist: "Daft Punk",
    year: "2010",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "NICHE",
    pop: 6,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12140,
    title: "Derezzed (Avicii Remix)",
    artist: "Daft Punk",
    year: "2011",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "NICHE",
    pop: 6,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12141,
    title: "Harder, Better, Faster, Stronger (Live)",
    artist: "Daft Punk",
    year: "2007",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12142,
    title: "Around the World / HBFS (Live)",
    artist: "Daft Punk",
    year: "2007",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "CLASSIC",
    pop: 8,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12143,
    title: "Aerodynamic",
    artist: "Daft Punk",
    year: "2001",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "BANGER",
    pop: 7,
    ability: A,
    abilityDesc: P,
  },
  {
    id: 12144,
    title: "Aerodynamic Breakdown",
    artist: "Daft Punk",
    year: "2001",
    kind: "Wishlist",
    genre: "Electronic",
    rarity: "NICHE",
    pop: 6,
    ability: A,
    abilityDesc: P,
  },
];
