import type { CardData } from "@/components/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const CLASSICAL_CARDS: CardData[] = [
  {
    id: 38,
    title: "God Save the King",
    year: 1745,
    genre: "Anthem",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 5,
    tracksOut: [39],
    rarity: "Banger",
    artwork: `${ART}artwork.god-save-the-king-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.god-save-the-king-v1.png"],
    ...(artworkPromptFor(38) ?? {}),
    catalogNumber: 2,
    catalogSeriesLabel: "Classical",
  },
  {
    id: 39,
    title: "God Save the Queen",
    year: 1745,
    genre: "Anthem",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 5,
    tracksOut: [38, 29],
    rarity: "Banger",
    artwork: `${ART}artwork.god-save-the-queen-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.god-save-the-queen-v1.png"],
    ...(artworkPromptFor(39) ?? {}),
    catalogNumber: 3,
    catalogSeriesLabel: "Classical",
  },
  {
    id: 54,
    title: "Spring (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1725,
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-spring-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-spring-v1.png"],
    ...(artworkPromptFor(54) ?? {}),
    catalogNumber: 4,
    catalogSeriesLabel: "Classical",
  },
  {
    id: 55,
    title: "Summer (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1725,
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-summer-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-summer-v1.png"],
    ...(artworkPromptFor(55) ?? {}),
    catalogNumber: 5,
    catalogSeriesLabel: "Classical",
  },
  {
    id: 56,
    title: "Autumn (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1725,
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-autumn-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-autumn-v1.png"],
    ...(artworkPromptFor(56) ?? {}),
    catalogNumber: 6,
    catalogSeriesLabel: "Classical",
  },
  {
    id: 57,
    title: "Winter (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1725,
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-winter-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-winter-v1.png"],
    ...(artworkPromptFor(57) ?? {}),
    catalogNumber: 7,
    catalogSeriesLabel: "Classical",
  },
  {
    id: 65,
    title: "Lacrimosa",
    artist: "Wolfgang Amadeus Mozart",
    year: 1791,
    genre: "Sacred Choral",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.mozart-requiem-lacrimosa-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.mozart-requiem-lacrimosa-v1.png"],
    catalogNumber: 8,
    catalogSeriesLabel: "Classical",
  },
  {
    id: 66,
    title: "Dies Irae",
    artist: "Giuseppe Verdi",
    year: 1874,
    genre: "Romantic Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.verdi-dies-irae-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.verdi-dies-irae-v1.png"],
    ...(artworkPromptFor(66) ?? {}),
    catalogNumber: 9,
    catalogSeriesLabel: "Classical",
  },
  {
    id: 72,
    title: "Symphony No. 5",
    artist: "Ludwig van Beethoven",
    year: 1808,
    genre: "Symphonic Showpiece",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.beethoven-symphony-no-5-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.beethoven-symphony-no-5-v1.png"],
    ...(artworkPromptFor(72) ?? {}),
    artworkOffsetY: -25,
    catalogNumber: 10,
    catalogSeriesLabel: "Classical",
  },
  {
    id: 73,
    title: "O Fortuna",
    artist: "Carl Orff",
    year: 1937,
    genre: "Symphonic Showpiece",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.carmina-burana-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.carmina-burana-v1.png"],
    catalogNumber: 11,
    catalogSeriesLabel: "Classical",
  },
];
