import type { CardData } from "@/components/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

const CATALOG_SERIES_LABEL = "Disco/Funk";

export const DISCO_FUNK_CARDS: CardData[] = ([
  {
    catalogNumber: 2,
    id: 6,
    title: "Night Fever",
    artist: "Bee Gees",
    year: 1977,
    genre: "Disco",
    ability: "Groove",
    abilityDesc: "Boosts all Funk cards on the field by +5 popularity.",
    pop: 9,
    rarity: "Banger",
    artwork: `${ART}artwork.night-fever-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.night-fever-v1.png"],
  },
  {
    catalogNumber: 4,
    id: 43,
    title: "My Heart Will Go On",
    artist: "Celine Dion",
    year: 1997,
    genre: "Disco Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.celine-dion-my-hearth-will-go-on-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.celine-dion-my-hearth-will-go-on-v1.png"],
    ...(artworkPromptFor(43) ?? {}),
  },
  {
    catalogNumber: 5,
    id: 47,
    title: "Thriller",
    artist: "Michael Jackson",
    year: 1982,
    genre: "Disco Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.michael-jackson-thriller-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.michael-jackson-thriller-v1.png"],
    ...(artworkPromptFor(47) ?? {}),
  },
  {
    catalogNumber: 6,
    id: 81,
    tracksOut: [82],
    title: "Shaft",
    artist: "Isaac Hayes",
    year: 1971,
    genre: "Disco",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    artworkOffsetY: -25,
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.isaac-hays-shaft-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.isaac-hays-shaft-v1.png"],
    ...(artworkPromptFor(81) ?? {}),
  },
  {
    catalogNumber: 7,
    id: 91,
    tracksOut: [93, 92],
    title: "Superstition",
    artist: "Stevie Wonder",
    year: 1972,
    genre: "Funk Soul",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.stevie-wonder-superstition-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.stevie-wonder-superstition-v1.png"],
    ...(artworkPromptFor(91) ?? {}),
  },
  {
    catalogNumber: 8,
    id: 112,
    tracksOut: [111],
    title: "Cola Bottle Baby",
    artist: "Edwin Birdsong",
    year: 1979,
    genre: "Funk Soul",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.cola-bottle-baby-edwin-birdsong-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.cola-bottle-baby-edwin-birdsong-v1.png"],
    ...(artworkPromptFor(112) ?? {}),
  },
  {
    catalogNumber: 9,
    id: 116,
    title: "A Fifth of Beethoven",
    artist: "Walter Murphy",
    year: 1976,
    genre: "Disco",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.walter-murphy-a-fifth-of-beethoven-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.walter-murphy-a-fifth-of-beethoven-v1.png"],
    ...(artworkPromptFor(116) ?? {}),
  },
  {
    catalogNumber: 10,
    id: 2,
    title: "Billie Jean",
    artist: "Michael Jackson",
    year: 1982,
    genre: "Disco Pop",
    ability: "Crossover",
    abilityDesc: "Gains +10 popularity when played after a dance track.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.billy-jean-v2.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.billy-jean-v2.png"],
  },
] as CardData[]).map((c) => ({ ...c, catalogSeriesLabel: CATALOG_SERIES_LABEL }));
