import type { CardData } from "@/components/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const ELECTRONIC_CARDS: CardData[] = [
  {
    id: 3,
    title: "One More Time",
    artist: "Daft Punk",
    year: 2000,
    genre: "House",
    ability: "Loop Sync",
    abilityDesc: "Repeats its effect once if experimental is above 60.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.daft-punk-one-more-time-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.daft-punk-one-more-time-v1.png"],
    ...(artworkPromptFor(3) ?? {}),
    catalogNumber: 1,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 37,
    title: "Sky and Sand",
    artist: "Paul Kalkbrenner",
    year: 2008,
    genre: "Minimal",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.paul-karlkbrenner-sky-and-sand-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.paul-karlkbrenner-sky-and-sand-v1.png"],
    ...(artworkPromptFor(37) ?? {}),
    catalogNumber: 2,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 42,
    title: "Levels",
    artist: "Avicii",
    year: 2011,
    genre: "EDM",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.avicii-levels-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.avicii-levels-v1.png"],
    ...(artworkPromptFor(42) ?? {}),
    catalogNumber: 3,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 45,
    title: "Gangnam Style",
    artist: "PSY",
    year: 2012,
    genre: "Electropop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.psy-gagnam-style-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.psy-gagnam-style-v1.png"],
    ...(artworkPromptFor(45) ?? {}),
    catalogNumber: 4,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 46,
    title: "Poker Face",
    artist: "Lady Gaga",
    year: 2008,
    genre: "Dance Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.lady-gaga-poker-face-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.lady-gaga-poker-face-v1.png"],
    ...(artworkPromptFor(46) ?? {}),
    catalogNumber: 5,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 49,
    title: "Shape of You",
    artist: "Ed Sheeran",
    year: 2017,
    genre: "Electropop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.shape-of-you-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.shape-of-you-v1.png"],
    catalogNumber: 6,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 53,
    title: "Bella Ciao",
    artist: "El Profesor",
    year: 2017,
    genre: "Electropop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.bella-ciao-casa-de-papel-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.bella-ciao-casa-de-papel-v1.png"],
    ...(artworkPromptFor(53) ?? {}),
    catalogNumber: 7,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 58,
    title: "Shake It Off",
    artist: "Taylor Swift",
    year: 2014,
    genre: "Dance Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.taylor-swift-shake-it-off-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.taylor-swift-shake-it-off-v1.png"],
    catalogNumber: 8,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 59,
    title: "Sandstorm",
    artist: "Darude",
    year: 1999,
    genre: "EDM",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.darude-sandstorm-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.darude-sandstorm-v1.png"],
    ...(artworkPromptFor(59) ?? {}),
    catalogNumber: 9,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 82,
    title: "Shaft",
    artist: "Malik Adouane",
    year: 1993,
    genre: "Hard Techno",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    artworkOffsetY: -25,
    pop: 6,
    rarity: "Banger",
    artwork: `${ART}artwork.shaft-malik-adouane-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.shaft-malik-adouane-v1.png"],
    ...(artworkPromptFor(82) ?? {}),
    catalogNumber: 11,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 84,
    title: "Opus I",
    artist: "Eric Prydz",
    year: 2015,
    genre: "EDM",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    tracksOut: [85],
    rarity: "Legendary",
    artwork: `${ART}artwork.eric-prydz-opus-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.eric-prydz-opus-v1.png"],
    catalogNumber: 12,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 85,
    title: "Opus II",
    artist: "Four Tet",
    year: 2016,
    genre: "Progressive House",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    tracksOut: [86],
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.four-tet-opus-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.four-tet-opus-v1.png"],
    catalogNumber: 13,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 86,
    title: "Opus III",
    artist: "Lunatic",
    year: 2024,
    genre: "Peak Time Techno",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.lunatic-opus-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.lunatic-opus-v1.png"],
    catalogNumber: 14,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 90,
    title: "Vois sur ton chemin",
    artist: "BENNETT",
    year: 2023,
    genre: "Hard Techno",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.bennet-vois-sur-ton-chemin-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.bennet-vois-sur-ton-chemin-v1.png"],
    ...(artworkPromptFor(90) ?? {}),
    catalogNumber: 15,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 93,
    title: "Superstition",
    artist: "C2C",
    year: 2012,
    genre: "Turntablism",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.c2c-superstition-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.c2c-superstition-v1.png"],
    ...(artworkPromptFor(93) ?? {}),
    catalogNumber: 16,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 108,
    title: "Losing Your Mind",
    artist: "Adam Beyer",
    year: 2021,
    genre: "Peak Time Techno",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.adam-beyer-loosing-your-mind-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.adam-beyer-loosing-your-mind-v1.png"],
    artworkOffsetY: -50,
    ...(artworkPromptFor(108) ?? {}),
    catalogNumber: 17,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 109,
    title: "Mad World",
    artist: "Tears for Fears",
    year: 1982,
    genre: "New Wave",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    tracksOut: [110],
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.tears-for-fears-mad-world-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.tears-for-fears-mad-world-v1.png"],
    ...(artworkPromptFor(109) ?? {}),
    catalogNumber: 18,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 110,
    title: "Mad World",
    artist: "Gary Jules",
    year: 2001,
    genre: "Chamber Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.gary-jules-mad-world-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.gary-jules-mad-world-v1.png"],
    ...(artworkPromptFor(110) ?? {}),
    catalogNumber: 19,
    catalogSeriesLabel: "Electronic",
  },
  {
    id: 111,
    title: "Harder, Better, Faster, Stronger",
    artist: "Daft Punk",
    year: 2001,
    genre: "French House",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    tracksOut: [113],
    rarity: "Legendary",
    artwork: `${ART}artwork.daft-punk-harder-better-faster-stronger-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT[
        "artwork.daft-punk-harder-better-faster-stronger-v1.png"
      ],
    catalogNumber: 20,
    catalogSeriesLabel: "Electronic",
  },
];
