import type { CardData } from "@/components/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const HIP_HOP_CARDS: CardData[] = [
  {
    id: 5,
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    year: 2017,
    genre: "Trap",
    ability: "Lyrical",
    abilityDesc:
      "Drains 15 power from the opponent when popularity is 7 or higher.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.kendrick-lamar-humble-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.kendrick-lamar-humble-v1.png"],
    ...(artworkPromptFor(5) ?? {}),
    catalogNumber: 1,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 40,
    title: "Au DD",
    artist: "PNL",
    year: 2019,
    genre: "Cloud Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.pnl-au-dd-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.pnl-au-dd-v1.png"],
    catalogNumber: 4,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 41,
    title: "Maria Maria",
    artist: "Santana feat. The Product G&B",
    year: 1999,
    genre: "R&B",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.carlos-santana-maria-maria-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.carlos-santana-maria-maria-v1.png"],
    ...(artworkPromptFor(41) ?? {}),
    catalogNumber: 5,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 44,
    title: "Lose Yourself",
    artist: "Eminem",
    year: 2002,
    genre: "Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.eminem-lose-yourself-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.eminem-lose-yourself-v1.png"],
    ...(artworkPromptFor(44) ?? {}),
    catalogNumber: 6,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 48,
    title: "Sicko Mode",
    artist: "Travis Scott",
    year: 2018,
    genre: "Cloud Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Classic",
    artwork: `${ART}artwork.sicko-mode-travis-scott-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.sicko-mode-travis-scott-v1.png"],
    ...(artworkPromptFor(48) ?? {}),
    catalogNumber: 7,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 67,
    title: "Cry Me a River",
    artist: "Justin Timberlake",
    year: 2002,
    genre: "R&B",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.justin-timberlake-cry-me-a-river-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.justin-timberlake-cry-me-a-river-v1.png"],
    ...(artworkPromptFor(67) ?? {}),
    catalogNumber: 9,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 70,
    title: "Without Me",
    artist: "Eminem",
    year: 2002,
    genre: "Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.without-me-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.without-me-v1.png"],
    catalogNumber: 10,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 79,
    title: "California Love",
    artist: "2Pac feat. Dr. Dre",
    year: 1995,
    genre: "Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    artworkOffsetY: -25,
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.dr-dre-tupac-california-love-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.dr-dre-tupac-california-love-v1.png"],
    ...(artworkPromptFor(79) ?? {}),
    catalogNumber: 11,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 88,
    title: "The Next Episode",
    artist: "Dr. Dre feat. Snoop Dogg",
    year: 1999,
    genre: "Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.dr-dre-next-episode-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.dr-dre-next-episode-v1.png"],
    ...(artworkPromptFor(88) ?? {}),
    catalogNumber: 12,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 107,
    title: "Losing Your Mind",
    artist: "Raury & Jaden",
    year: 2014,
    genre: "Alternative Hip-Hop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    tracksOut: [108],
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.raury-jaden-losing-your-mind-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.raury-jaden-losing-your-mind-v1.png"],
    artworkOffsetY: -40,
    ...(artworkPromptFor(107) ?? {}),
    catalogNumber: 17,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 113,
    title: "Stronger",
    artist: "Kanye West",
    year: 2007,
    genre: "Progressive Hip-Hop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.kanye-west-stronger-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.kanye-west-stronger-v1.png"],
    ...(artworkPromptFor(113) ?? {}),
    catalogNumber: 16,
    catalogSeriesLabel: "Hip-Hop",
  },
  {
    id: 115,
    title: "Straight Outta Compton",
    artist: "N.W.A",
    year: 1988,
    genre: "Gangsta Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.nwa-straight-outta-compton-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.nwa-straight-outta-compton-v1.png"],
    ...(artworkPromptFor(115) ?? {}),
    catalogNumber: 18,
    catalogSeriesLabel: "Hip-Hop",
  },
];
