import type { CardData } from "@/components/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const MAINSTREAM_CARDS: CardData[] = [
  {
    catalogNumber: 1,
    id: 78,
    title: "Hakuna Matata",
    artist: "The Lion King cast",
    year: 1994,
    genre: "Mainstream",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.hakuna-matata-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.hakuna-matata-v1.png"],
    ...(artworkPromptFor(78) ?? {}),
    catalogSeriesLabel: "Pop",
  },
  {
    catalogNumber: 2,
    id: 101,
    title: "The Great Pretender",
    artist: "Freddie Mercury",
    year: 1987,
    genre: "Mainstream",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.freddy-mercury-the-great-pretender-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.freddy-mercury-the-great-pretender-v1.png"],
    ...(artworkPromptFor(101) ?? {}),
    catalogSeriesLabel: "Pop",
  },
  {
    catalogNumber: 1,
    id: 49,
    title: "Shape of You",
    artist: "Ed Sheeran",
    year: 2017,
    genre: "Mainstream",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.shape-of-you-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.shape-of-you-v1.png"],
    catalogSeriesLabel: "Electronic",
  },
];
