import type { CardData } from "@/components/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const VINTAGE_CARDS: CardData[] = [
  {
    catalogNumber: 1,
    id: 7,
    title: "Ride of the Valkyries",
    artist: "Wagner",
    year: 1876,
    genre: "Soul",
    ability: "Fortissimo",
    abilityDesc: "Deals damage in three separate strikes of 60% power each.",
    pop: 6,
    rarity: "Legendary",
    artwork: `${ART}artwork.wagner-ride-of-the-valkyries-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.wagner-ride-of-the-valkyries-v1.png"],
    ...(artworkPromptFor(7) ?? {}),
    catalogSeriesLabel: "Vintage",
  },
  {
    id: 8,
    title: "So What",
    artist: "Miles Davis",
    year: 1959,
    genre: "Jazz",
    ability: "Modal",
    abilityDesc: "Random multiplier between ×1 and ×3 on each use.",
    pop: 5,
    rarity: "Classic",
    artwork: `${ART}artwork.miles-davis-so-what-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.miles-davis-so-what-v1.png"],
    ...(artworkPromptFor(8) ?? {}),
    catalogNumber: 2,
    catalogSeriesLabel: "Vintage",
  },
  {
    id: 61,
    title: "These Boots Are Made for Walkin'",
    artist: "Nancy Sinatra",
    year: 1966,
    genre: "Traditional Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.these-boots-are-made-for-walkin-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.these-boots-are-made-for-walkin-v1.png"],
    catalogNumber: 4,
    catalogSeriesLabel: "Vintage",
  },
  {
    id: 62,
    title: "These Boots Are Made for Walkin' (alt)",
    artist: "Nancy Sinatra",
    year: 1966,
    genre: "Traditional Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.these-boots-are-made-for-walkin-v2.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.these-boots-are-made-for-walkin-v2.png"],
    catalogNumber: 5,
    catalogSeriesLabel: "Vintage",
  },
  {
    id: 89,
    title: "The Edge",
    artist: "David McCallum",
    year: 1968,
    genre: "Jazz",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.david-mccallum-the-edge-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.david-mccallum-the-edge-v1.png"],
    artworkOffsetY: -20,
    catalogNumber: 6,
    catalogSeriesLabel: "Vintage",
  },
  {
    id: 114,
    title: "Amen, Brother",
    artist: "The Winstons",
    year: 1969,
    genre: "Early Funk",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    tracksOut: [115],
    rarity: "Legendary",
    artwork: `${ART}artwork.the-winstons-amen-brother-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.the-winstons-amen-brother-v1.png"],
    ...(artworkPromptFor(114) ?? {}),
    catalogNumber: 18,
    catalogSeriesLabel: "Vintage",
  },
];
