import type { CardRarity } from "@/lib/cards/card-rarity";
import { CARD_ARTWORK_BASE } from "@/lib/cards/art-path";
/** Source rows for planned / wishlist catalogue lines (many ship without artwork). */
export type WishlistCardDef = {
  rowKey: string;
  id: number;
  title: string;
  artist?: string;
  year: number;
  kind: "Genre" | "World" | "World blend" | "World + genre" | "Planned";
  /** Subgenre, or an app-level genre when the card is World+genre only. */
  genre?: string;
  country?: string;
  rarity: CardRarity;
  pop?: number;
  ability: string;
  abilityDesc: string;
  artwork?: string;
};

const P = "Planned catalogue entry.";
const A = "Reserve";

/** IDs 12xxx avoid collision with shipped deck (1–33, 9101). */
export const WISHLIST_CARD_DEFS: WishlistCardDef[] = [
  {
    rowKey: "wl-sky-and-sand",
    id: 12001,
    title: "Sky and Sand",
    artist: "Paul Kalkbrenner",
    year: 2008,
    kind: "Planned",
    genre: "Minimal",
    rarity: "Classic",
    pop: 78,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-africa",
    id: 12002,
    title: "Africa",
    artist: "Toto",
    year: 1982,
    kind: "Planned",
    genre: "Arena anthem",
    rarity: "Classic",
    pop: 93,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-god-saves-king",
    id: 12003,
    title: "God Save the King",
    year: 1745,
    kind: "Planned",
    genre: "Anthem",
    rarity: "Banger",
    pop: 55,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-god-saves-queen-anthem",
    id: 12004,
    title: "God Save the Queen",
    year: 1745,
    kind: "Planned",
    genre: "Anthem",
    rarity: "Banger",
    pop: 55,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-au-dd",
    id: 12005,
    title: "Au DD",
    artist: "PNL",
    year: 2019,
    kind: "Planned",
    genre: "Cloud rap",
    rarity: "Banger",
    pop: 88,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-sous-les-sunlights",
    id: 12006,
    title: "Sous les sunlights des tropiques",
    artist: "Gilbert Montagné",
    year: 1984,
    kind: "Planned",
    genre: "Disco",
    rarity: "Banger",
    pop: 76,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-next-episode",
    id: 12007,
    title: "The Next Episode",
    artist: "Dr. Dre feat. Snoop Dogg",
    year: 1999,
    kind: "Planned",
    genre: "Rap",
    rarity: "Legendary",
    pop: 91,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-shaft-isaac",
    id: 12008,
    title: "Shaft",
    artist: "Isaac Hayes",
    year: 1971,
    kind: "Planned",
    genre: "Disco",
    rarity: "Classic",
    pop: 84,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-shaft-malik",
    id: 12009,
    title: "Shaft",
    artist: "Malik Adouane",
    year: 1993,
    kind: "Planned",
    genre: "Techno",
    rarity: "Banger",
    pop: 62,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-jolene",
    id: 12010,
    title: "Jolene",
    artist: "Dolly Parton",
    year: 1973,
    kind: "Planned",
    genre: "Disco Pop",
    rarity: "Classic",
    pop: 86,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-rappers-delight",
    id: 12011,
    title: "Rapper's Delight",
    artist: "The Sugarhill Gang",
    year: 1979,
    kind: "Planned",
    genre: "Rap",
    rarity: "Legendary",
    pop: 85,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-highway-to-hell",
    id: 12012,
    title: "Highway to Hell",
    artist: "AC/DC",
    year: 1979,
    kind: "Planned",
    genre: "Classic rock",
    rarity: "Legendary",
    pop: 90,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-thunderstruck",
    id: 12013,
    title: "Thunderstruck",
    artist: "AC/DC",
    year: 1990,
    kind: "Planned",
    genre: "Arena anthem",
    rarity: "Classic",
    pop: 89,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-hells-bells",
    id: 12014,
    title: "Hell's Bells",
    artist: "AC/DC",
    year: 1980,
    kind: "Planned",
    genre: "Metal",
    rarity: "Classic",
    pop: 82,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-asereje",
    id: 12015,
    title: "Aserejé",
    artist: "Las Ketchup",
    year: 2002,
    kind: "Planned",
    genre: "Latin crossover",
    rarity: "Banger",
    pop: 88,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-ywnwa",
    id: 12016,
    title: "You'll Never Walk Alone",
    artist: "Gerry and the Pacemakers",
    year: 1963,
    kind: "Planned",
    genre: "Arena anthem",
    rarity: "Classic",
    pop: 80,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-sweet-caroline",
    id: 12017,
    title: "Sweet Caroline",
    artist: "Neil Diamond",
    year: 1969,
    kind: "Planned",
    genre: "Disco Pop",
    rarity: "Classic",
    pop: 87,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-baby-shark",
    id: 12018,
    title: "Baby Shark",
    artist: "Pinkfong",
    year: 2016,
    kind: "Planned",
    genre: "Electropop",
    rarity: "Banger",
    pop: 99,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-blinding-lights",
    id: 12019,
    title: "Blinding Lights",
    artist: "The Weeknd",
    year: 2019,
    kind: "Planned",
    genre: "Electropop",
    rarity: "Legendary",
    pop: 96,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-superstition",
    id: 12020,
    title: "Superstition",
    artist: "Stevie Wonder",
    year: 1972,
    kind: "Planned",
    genre: "Disco",
    rarity: "Legendary",
    pop: 88,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-rock-this-way",
    id: 12021,
    title: "Walk This Way",
    artist: "Aerosmith",
    year: 1975,
    kind: "Planned",
    genre: "Pop Rock",
    rarity: "Classic",
    pop: 83,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-walk-this-way-run",
    id: 12022,
    title: "Walk This Way",
    artist: "Run-DMC feat. Aerosmith",
    year: 1986,
    kind: "Planned",
    genre: "Rap",
    rarity: "Legendary",
    pop: 89,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-california-love",
    id: 12023,
    title: "California Love",
    artist: "2Pac feat. Dr. Dre",
    year: 1995,
    kind: "Planned",
    genre: "Rap",
    rarity: "Legendary",
    pop: 92,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-stairway",
    id: 12024,
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    year: 1971,
    kind: "Planned",
    genre: "Classic rock",
    rarity: "Legendary",
    pop: 94,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-pretender",
    id: 12025,
    title: "The Pretender",
    artist: "Foo Fighters",
    year: 2007,
    kind: "Planned",
    genre: "Arena anthem",
    rarity: "Classic",
    pop: 84,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-great-pretender-platters",
    id: 12026,
    title: "The Great Pretender",
    artist: "The Platters",
    year: 1955,
    kind: "Planned",
    genre: "Soul",
    rarity: "Classic",
    pop: 78,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-great-pretender-sinatra",
    id: 12027,
    title: "The Great Pretender",
    artist: "Frank Sinatra",
    year: 1958,
    kind: "Planned",
    genre: "Soul",
    rarity: "Classic",
    pop: 80,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-charge-triangle",
    id: 12028,
    title: "Chargé",
    artist: "Triangle des Bermudes",
    year: 2020,
    kind: "Planned",
    genre: "Rap",
    rarity: "Banger",
    pop: 70,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-my-way-sinatra",
    id: 12030,
    title: "My Way",
    artist: "Frank Sinatra",
    year: 1969,
    kind: "Planned",
    genre: "Soul",
    rarity: "Legendary",
    pop: 88,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-my-way-sid",
    id: 12031,
    title: "My Way",
    artist: "Sid Vicious",
    year: 1978,
    kind: "Planned",
    genre: "Punk",
    rarity: "Classic",
    pop: 72,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-la-mer-trenet",
    id: 12032,
    title: "La Mer",
    artist: "Charles Trenet",
    year: 1946,
    kind: "World",
    country: "France",
    genre: "French Variety",
    rarity: "Classic",
    pop: 82,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-beyond-the-sea",
    id: 12033,
    title: "Beyond the Sea",
    artist: "Bobby Darin",
    year: 1960,
    kind: "Planned",
    genre: "Traditional song",
    rarity: "Classic",
    pop: 86,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-hallelujah-cohen",
    id: 12034,
    title: "Hallelujah",
    artist: "Leonard Cohen",
    year: 1984,
    kind: "Planned",
    genre: "Pop Rock",
    rarity: "Legendary",
    pop: 88,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-hallelujah-buckley",
    id: 12035,
    title: "Hallelujah",
    artist: "Jeff Buckley",
    year: 1994,
    kind: "Planned",
    genre: "Pop Rock",
    rarity: "Legendary",
    pop: 90,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-maria-maria",
    id: 12036,
    title: "Maria Maria",
    artist: "Santana feat. The Product G&B",
    year: 1999,
    kind: "Planned",
    genre: "Latin crossover",
    rarity: "Classic",
    pop: 87,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-levels",
    id: 12037,
    title: "Levels",
    artist: "Avicii",
    year: 2011,
    kind: "Planned",
    genre: "EDM",
    rarity: "Legendary",
    pop: 91,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-my-heart-will-go-on",
    id: 12038,
    title: "My Heart Will Go On",
    artist: "Celine Dion",
    year: 1997,
    kind: "Planned",
    genre: "Disco Pop",
    rarity: "Legendary",
    pop: 94,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-lose-yourself",
    id: 12039,
    title: "Lose Yourself",
    artist: "Eminem",
    year: 2002,
    kind: "Planned",
    genre: "Rap",
    rarity: "Legendary",
    pop: 93,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-gangnam-style",
    id: 12040,
    title: "Gangnam Style",
    artist: "PSY",
    year: 2012,
    kind: "Planned",
    genre: "Electropop",
    rarity: "Legendary",
    pop: 95,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-abdel-kader",
    id: 12041,
    title: "Abdel Kader",
    artist: "Rachid Taha, Khaled, Faudel",
    year: 1998,
    kind: "Planned",
    genre: "Latin crossover",
    rarity: "Classic",
    pop: 80,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-bohemian-rhapsody-alt",
    id: 12042,
    title: "Bohemian Rhapsody",
    artist: "Queen",
    year: 1975,
    kind: "Planned",
    genre: "Pop Rock",
    rarity: "Legendary",
    pop: 92,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-poker-face",
    id: 12043,
    title: "Poker Face",
    artist: "Lady Gaga",
    year: 2008,
    kind: "Planned",
    genre: "Electropop",
    rarity: "Legendary",
    pop: 92,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-despacito",
    id: 12044,
    title: "Despacito",
    artist: "Luis Fonsi feat. Daddy Yankee",
    year: 2017,
    kind: "Planned",
    genre: "Latin crossover",
    rarity: "Legendary",
    pop: 96,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-thriller",
    id: 12045,
    title: "Thriller",
    artist: "Michael Jackson",
    year: 1982,
    kind: "Planned",
    genre: "Disco Pop",
    rarity: "Legendary",
    pop: 95,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-sicko-mode",
    id: 12046,
    title: "Sicko Mode",
    artist: "Travis Scott",
    year: 2018,
    kind: "Planned",
    genre: "Cloud rap",
    rarity: "Classic",
    pop: 89,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-take-five",
    id: 12047,
    title: "Take Five",
    artist: "The Dave Brubeck Quartet",
    year: 1959,
    kind: "Planned",
    genre: "Jazz",
    rarity: "Legendary",
    pop: 78,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-mission-impossible",
    id: 12048,
    title: "Mission: Impossible",
    artist: "Lalo Schifrin",
    year: 1966,
    kind: "Planned",
    genre: "Symphonic showpiece",
    rarity: "Classic",
    pop: 82,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-blue-da-ba-dee",
    id: 12049,
    title: "Blue (Da Ba Dee)",
    artist: "Eiffel 65",
    year: 1999,
    kind: "Planned",
    genre: "Electropop",
    rarity: "Banger",
    pop: 86,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-shape-of-you",
    id: 12050,
    title: "Shape of You",
    artist: "Ed Sheeran",
    year: 2017,
    kind: "Planned",
    genre: "Electropop",
    rarity: "Legendary",
    pop: 95,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-hakuna-matata",
    id: 12054,
    title: "Hakuna Matata",
    artist: "The Lion King cast",
    year: 1994,
    kind: "Planned",
    genre: "Movie",
    rarity: "Banger",
    pop: 88,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-tribu-de-dana",
    id: 12055,
    title: "La Tribu de Dana",
    artist: "Manau",
    year: 1998,
    kind: "Planned",
    genre: "Rap",
    rarity: "Banger",
    pop: 84,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-bella-ciao-original",
    id: 12056,
    title: "Bella Ciao",
    artist: "Traditional (Italy)",
    year: 1880,
    kind: "Planned",
    genre: "Traditional song",
    rarity: "Banger",
    pop: 72,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-bella-ciao-casa",
    id: 12057,
    title: "Bella Ciao",
    artist: "El Profesor",
    year: 2017,
    kind: "Planned",
    genre: "Electropop",
    rarity: "Banger",
    pop: 86,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-vivaldi-spring",
    id: 12058,
    title: "Spring (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1723,
    kind: "Planned",
    genre: "Baroque classical",
    rarity: "Banger",
    pop: 68,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-vivaldi-summer",
    id: 12059,
    title: "Summer (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1723,
    kind: "Planned",
    genre: "Baroque classical",
    rarity: "Banger",
    pop: 68,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-vivaldi-autumn",
    id: 12060,
    title: "Autumn (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1723,
    kind: "Planned",
    genre: "Baroque classical",
    rarity: "Banger",
    pop: 68,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-vivaldi-winter",
    id: 12061,
    title: "Winter (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1723,
    kind: "Planned",
    genre: "Baroque classical",
    rarity: "Banger",
    pop: 70,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-entertainer",
    id: 12062,
    title: "The Entertainer",
    artist: "Scott Joplin",
    year: 1902,
    kind: "Planned",
    genre: "Ragtime",
    rarity: "Banger",
    pop: 74,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-maple-leaf-rag",
    id: 12063,
    title: "Maple Leaf Rag",
    artist: "Scott Joplin",
    year: 1899,
    kind: "Planned",
    genre: "Ragtime",
    rarity: "Banger",
    pop: 72,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-clair-de-lune",
    id: 12064,
    title: "Clair de Lune",
    artist: "Claude Debussy",
    year: 1905,
    kind: "Planned",
    genre: "Impressionist classical",
    rarity: "Classic",
    pop: 76,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-gymnopedie",
    id: 12065,
    title: "Gymnopédie No. 1",
    artist: "Erik Satie",
    year: 1888,
    kind: "Planned",
    genre: "Impressionist classical",
    rarity: "Classic",
    pop: 74,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-fur-elise",
    id: 12066,
    title: "Für Elise",
    artist: "Ludwig van Beethoven",
    year: 1810,
    kind: "Planned",
    genre: "Romantic classical",
    rarity: "Banger",
    pop: 88,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-moonlight-sonata",
    id: 12067,
    title: "Moonlight Sonata",
    artist: "Ludwig van Beethoven",
    year: 1801,
    kind: "Planned",
    genre: "Romantic classical",
    rarity: "Legendary",
    pop: 86,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-la-campanella",
    id: 12068,
    title: "La Campanella",
    artist: "Franz Liszt",
    year: 1851,
    kind: "Planned",
    genre: "Virtuoso piano",
    rarity: "Legendary",
    pop: 78,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-air-on-g-string",
    id: 12069,
    title: "Air on the G String",
    artist: "J.S. Bach",
    year: 1871,
    kind: "Planned",
    genre: "Baroque classical",
    rarity: "Classic",
    pop: 80,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-hungarian-dance-5",
    id: 12070,
    title: "Hungarian Dance No. 5",
    artist: "Johannes Brahms",
    year: 1869,
    kind: "Planned",
    genre: "Romantic classical",
    rarity: "Classic",
    pop: 82,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-mountain-king",
    id: 12071,
    title: "In the Hall of the Mountain King",
    artist: "Edvard Grieg",
    year: 1875,
    kind: "Planned",
    genre: "Symphonic showpiece",
    rarity: "Classic",
    pop: 84,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-pachelbel-canon",
    id: 12072,
    title: "Canon in D",
    artist: "Johann Pachelbel",
    year: 1680,
    kind: "Planned",
    genre: "Baroque classical",
    rarity: "Legendary",
    pop: 87,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-nocturne-chopin",
    id: 12073,
    title: "Nocturne Op. 9 No. 2",
    artist: "Frédéric Chopin",
    year: 1832,
    kind: "Planned",
    genre: "Romantic classical",
    rarity: "Legendary",
    pop: 80,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-swan-lake",
    id: 12074,
    title: "Swan Lake Theme",
    artist: "Pyotr Ilyich Tchaikovsky",
    year: 1876,
    kind: "Planned",
    genre: "Ballet",
    rarity: "Classic",
    pop: 82,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-blue-danube",
    id: 12075,
    title: "The Blue Danube",
    artist: "Johann Strauss II",
    year: 1866,
    kind: "Planned",
    genre: "Waltz",
    rarity: "Classic",
    pop: 83,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-bolero",
    id: 12076,
    title: "Boléro",
    artist: "Maurice Ravel",
    year: 1928,
    kind: "Planned",
    genre: "Symphonic showpiece",
    rarity: "Legendary",
    pop: 79,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-carmen-overture",
    id: 12077,
    title: "Carmen Overture",
    artist: "Georges Bizet",
    year: 1875,
    kind: "Planned",
    genre: "Opera",
    rarity: "Classic",
    pop: 81,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-greensleeves",
    id: 12078,
    title: "Greensleeves",
    artist: "Traditional (England)",
    year: 1580,
    kind: "Planned",
    genre: "Traditional song",
    rarity: "Banger",
    pop: 70,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-silent-night",
    id: 12079,
    title: "Silent Night",
    artist: "Franz Xaver Gruber",
    year: 1818,
    kind: "Planned",
    genre: "Christian hymn",
    rarity: "Banger",
    pop: 85,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-when-the-saints",
    id: 12080,
    title: "When the Saints Go Marching In",
    artist: "Traditional",
    year: 1896,
    kind: "Planned",
    genre: "Spiritual",
    rarity: "Banger",
    pop: 76,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-frere-jacques",
    id: 12081,
    title: "Frère Jacques",
    artist: "Traditional (France)",
    year: 1780,
    kind: "Planned",
    genre: "Traditional song",
    rarity: "Banger",
    pop: 65,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-danny-boy",
    id: 12082,
    title: "Londonderry Air (Danny Boy)",
    artist: "Traditional (Ireland)",
    year: 1855,
    kind: "Planned",
    genre: "Folk ballad",
    rarity: "Banger",
    pop: 74,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-o-sole-mio",
    id: 12083,
    title: "O Sole Mio",
    artist: "Eduardo di Capua",
    year: 1898,
    kind: "World",
    country: "Italy",
    genre: "Neapolitan song",
    rarity: "Classic",
    pop: 78,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-sorcerers-apprentice",
    id: 12084,
    title: "The Sorcerer's Apprentice",
    artist: "Paul Dukas",
    year: 1897,
    kind: "Planned",
    genre: "Symphonic showpiece",
    rarity: "Legendary",
    pop: 77,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-pomp-circumstance",
    id: 12085,
    title: "Pomp and Circumstance",
    artist: "Edward Elgar",
    year: 1901,
    kind: "Planned",
    genre: "March",
    rarity: "Classic",
    pop: 79,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-stars-stripes",
    id: 12086,
    title: "The Stars and Stripes Forever",
    artist: "John Philip Sousa",
    year: 1896,
    kind: "Planned",
    genre: "March",
    rarity: "Classic",
    pop: 78,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-ave-maria-schubert",
    id: 12087,
    title: "Ave Maria",
    artist: "Franz Schubert",
    year: 1825,
    kind: "Planned",
    genre: "Sacred choral",
    rarity: "Classic",
    pop: 84,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-william-tell-overture",
    id: 12088,
    title: "William Tell Overture",
    artist: "Gioachino Rossini",
    year: 1829,
    kind: "Planned",
    genre: "Opera",
    rarity: "Classic",
    pop: 83,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-toccata-fugue-d-minor",
    id: 12089,
    title: "Toccata and Fugue in D minor",
    artist: "J.S. Bach",
    year: 1707,
    kind: "Planned",
    genre: "Baroque classical",
    rarity: "Legendary",
    pop: 81,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-eine-kleine-nachtmusik",
    id: 12090,
    title: "Eine kleine Nachtmusik",
    artist: "Wolfgang Amadeus Mozart",
    year: 1787,
    kind: "Planned",
    genre: "Serenade",
    rarity: "Classic",
    pop: 85,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-ode-to-joy",
    id: 12091,
    title: "Ode to Joy",
    artist: "Ludwig van Beethoven",
    year: 1824,
    kind: "Planned",
    genre: "Symphonic showpiece",
    rarity: "Legendary",
    pop: 88,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-oh-susanna",
    id: 12092,
    title: "Oh! Susanna",
    artist: "Stephen Foster",
    year: 1848,
    kind: "Planned",
    genre: "Traditional song",
    rarity: "Banger",
    pop: 68,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-yankee-doodle",
    id: 12093,
    title: "Yankee Doodle",
    artist: "Traditional (USA)",
    year: 1755,
    kind: "Planned",
    genre: "Traditional song",
    rarity: "Banger",
    pop: 62,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-aura-lee",
    id: 12094,
    title: "Aura Lee",
    artist: "George R. Poulton",
    year: 1861,
    kind: "Planned",
    genre: "Folk ballad",
    rarity: "Niche",
    pop: 58,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-house-rising-sun",
    id: 12095,
    title: "House of the Rising Sun",
    artist: "Traditional",
    year: 1895,
    kind: "Planned",
    genre: "Folk ballad",
    rarity: "Classic",
    pop: 82,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-scarborough-fair",
    id: 12096,
    title: "Scarborough Fair",
    artist: "Traditional (England)",
    year: 1650,
    kind: "Planned",
    genre: "Folk ballad",
    rarity: "Classic",
    pop: 76,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-la-cucaracha",
    id: 12097,
    title: "La Cucaracha",
    year: 1880,
    kind: "Planned",
    genre: "Mexican Folk",
    rarity: "Banger",
    pop: 72,
    ability: A,
    abilityDesc: P,
    artwork: `${CARD_ARTWORK_BASE}artwork.la-cucaracha-v1.png`,
  },
  {
    rowKey: "wl-sakura-sakura",
    id: 12098,
    title: "Sakura Sakura",
    artist: "Traditional (Japan)",
    year: 1888,
    kind: "Planned",
    genre: "Traditional song",
    rarity: "Banger",
    pop: 66,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-habanera-carmen",
    id: 12099,
    title: "Habanera (Carmen)",
    artist: "Georges Bizet",
    year: 1875,
    kind: "Planned",
    genre: "Opera",
    rarity: "Classic",
    pop: 80,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-turkish-march-mozart",
    id: 12100,
    title: "Turkish March",
    artist: "Wolfgang Amadeus Mozart",
    year: 1783,
    kind: "Planned",
    genre: "Serenade",
    rarity: "Classic",
    pop: 79,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-waltz-of-the-flowers",
    id: 12101,
    title: "Waltz of the Flowers",
    artist: "Pyotr Ilyich Tchaikovsky",
    year: 1892,
    kind: "Planned",
    genre: "Ballet",
    rarity: "Classic",
    pop: 78,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-radetzky-march",
    id: 12102,
    title: "Radetzky March",
    artist: "Johann Strauss I",
    year: 1848,
    kind: "Planned",
    genre: "March",
    rarity: "Classic",
    pop: 77,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-toreador-song",
    id: 12103,
    title: "Toreador Song",
    artist: "Georges Bizet",
    year: 1875,
    kind: "Planned",
    genre: "Opera",
    rarity: "Classic",
    pop: 76,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-bridal-chorus",
    id: 12104,
    title: "Bridal Chorus",
    artist: "Richard Wagner",
    year: 1850,
    kind: "Planned",
    genre: "Opera",
    rarity: "Classic",
    pop: 84,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-ave-verum-corpus",
    id: 12105,
    title: "Ave Verum Corpus",
    artist: "Wolfgang Amadeus Mozart",
    year: 1791,
    kind: "Planned",
    genre: "Sacred choral",
    rarity: "Classic",
    pop: 75,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-jesu-joy",
    id: 12106,
    title: "Jesu, Joy of Man's Desiring",
    artist: "J.S. Bach",
    year: 1723,
    kind: "Planned",
    genre: "Sacred choral",
    rarity: "Classic",
    pop: 78,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-la-donna-e-mobile",
    id: 12107,
    title: "La Donna è Mobile",
    artist: "Giuseppe Verdi",
    year: 1851,
    kind: "Planned",
    genre: "Opera",
    rarity: "Classic",
    pop: 79,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-funiculi-funicula",
    id: 12108,
    title: "Funiculì Funiculà",
    artist: "Luigi Denza",
    year: 1880,
    kind: "World",
    country: "Italy",
    genre: "Neapolitan song",
    rarity: "Classic",
    pop: 77,
    ability: A,
    abilityDesc: P,
  },
  {
    rowKey: "wl-skaters-waltz",
    id: 12109,
    title: "The Skater's Waltz",
    artist: "Émile Waldteufel",
    year: 1882,
    kind: "Planned",
    genre: "Waltz",
    rarity: "Classic",
    pop: 74,
    ability: A,
    abilityDesc: P,
  },
];
