import type { CardData } from "@/components/Card";
import type { AppGenreName } from "@/lib/genres";
import { CARD_ARTWORK_BASE as ART } from "./art-path";

/** One fixture card per app genre (charter anatomy, rarity grid). */
export const MOCK_CARDS: Record<AppGenreName, CardData> = {
  Rock: {
    id: 1,
    title: "Bohemian Rhapsody",
    artist: "Queen",
    year: 1975,
    subgenre: "Pop Rock",
    ability: "Anthemic",
    abilityDesc: "Doubles momentum on any track with a guitar solo.",
    pop: 92,
    rarity: "Legendary",
    artwork: `${ART}artwork.bohemian-rhapsody-v2.png`,
  },
  Mainstream: {
    id: 2,
    title: "Billie Jean",
    artist: "Michael Jackson",
    year: 1982,
    subgenre: "Disco Pop",
    ability: "Crossover",
    abilityDesc: "Gains +10 popularity when played after a dance track.",
    pop: 97,
    rarity: "Legendary",
    artwork: `${ART}artwork.billy-jean-v2.png`,
  },
  Electronic: {
    id: 3,
    title: "One More Time",
    artist: "Daft Punk",
    year: 2000,
    subgenre: "House",
    ability: "Loop Sync",
    abilityDesc: "Repeats its effect once if experimental is above 60.",
    pop: 88,
    rarity: "Classic",
    artwork: `${ART}artwork.daft-punk-one-more-time-v1.png`,
  },
  "Reggae/Dub": {
    id: 4,
    title: "Is This Love",
    artist: "Bob Marley",
    year: 1978,
    subgenre: "Roots",
    ability: "Roots",
    abilityDesc: "Heals 20 HP when adjacent to a World genre card.",
    pop: 82,
    rarity: "Classic",
    artwork: `${ART}artwork.is-this-love-v1.png`,
  },
  "Hip-Hop": {
    id: 5,
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    year: 2017,
    subgenre: "R&B Soul",
    ability: "Lyrical",
    abilityDesc:
      "Drains 15 power from the opponent when popularity exceeds 70.",
    pop: 86,
    rarity: "Legendary",
    artwork: `${ART}artwork.kendrick-lamar-humble-v1.png`,
  },
  "Disco/Funk": {
    id: 6,
    title: "Night Fever",
    artist: "Bee Gees",
    year: 1977,
    subgenre: "Disco",
    ability: "Groove",
    abilityDesc: "Boosts all Funk cards on the field by +5 popularity.",
    pop: 90,
    rarity: "Banger",
    artwork: `${ART}artwork.night-fever-v1.png`,
  },
  Classical: {
    id: 7,
    title: "Ride of the Valkyries",
    artist: "Wagner",
    year: 1876,
    subgenre: "Soul",
    ability: "Fortissimo",
    abilityDesc: "Deals damage in three separate strikes of 60% power each.",
    pop: 58,
    rarity: "Legendary",
    artwork: `${ART}artwork.wagner-ride-of-the-valkyries-v1.png`,
  },
  Vintage: {
    id: 8,
    title: "So What",
    artist: "Miles Davis",
    year: 1959,
    subgenre: "Jazz",
    ability: "Modal",
    abilityDesc: "Random multiplier between ×1 and ×3 on each use.",
    pop: 55,
    rarity: "Classic",
    artwork: `${ART}artwork.miles-davis-so-what-v1.png`,
  },
};

/** World cards: country/region identity on the type strip (no genre mix). */
export const WORLD_FLAG_CARDS: CardData[] = [
  {
    id: 20,
    title: "Take Me Home, Country Roads",
    artist: "John Denver",
    year: 1971,
    subgenre: "Country",
    ability: "Heartland",
    abilityDesc: "Restores 10 HP to all allied cards when played.",
    pop: 78,
    rarity: "Banger",
    country: "USA",
    artwork: `${ART}artwork.take-me-home-country-roads-v1.png`,
  },
  {
    id: 24,
    title: "Les Lacs du Connemara",
    artist: "Michel Sardou",
    year: 1981,
    subgenre: "French Variety",
    ability: "Melancholy",
    abilityDesc: "Draws 2 cards from the deck when played after a Legendary.",
    pop: 74,
    rarity: "Banger",
    country: "France",
    artwork: `${ART}artwork.michel-sardou-les-lacs-du-connemara-v1.png`,
  },
  {
    id: 26,
    title: "Tri Martolod",
    artist: "Traditional",
    year: 1972,
    subgenre: "Folk Breton",
    ability: "Rising Tide",
    abilityDesc: "Gain +10 power for each allied World card in play.",
    pop: 58,
    rarity: "Banger",
    country: "Bretagne",
    artwork: `${ART}artwork.tri-martolod-v1.png`,
  },
];

/** World + genre/subgenre mixes (fade, dual identity on strip). */
export const WORLD_MIXED_CARDS: CardData[] = [
  {
    id: 27,
    title: "Bande Organisée",
    artist: "13 Organisé",
    year: 2020,
    subgenre: "Rap",
    ability: "Street Anthem",
    abilityDesc:
      "Allied Hip-Hop cards gain +12 popularity on the turn this card is played.",
    pop: 90,
    rarity: "Classic",
    country: "France",
    artwork: `${ART}artwork.13-organises-bande-organisee-v1.png`,
  },
  {
    id: 21,
    title: "Amazing Grace",
    artist: "Traditional",
    year: 1779,
    subgenre: "Religious",
    ability: "Redemption",
    abilityDesc: "Revives one defeated allied card with 30 HP.",
    pop: 72,
    rarity: "Classic",
    country: "USA",
    artwork: `${ART}artwork.amazing-grace-v1.png`,
  },
  {
    id: 23,
    title: "La Marseillaise",
    artist: "Rouget de Lisle",
    year: 1792,
    subgenre: "Anthem",
    ability: "Liberty",
    abilityDesc: "Grants +15 power to all allied cards on the next turn.",
    pop: 68,
    rarity: "Legendary",
    country: "France",
    artwork: `${ART}artwork.rouget-de-lisle-la-marseillaise-v1.png`,
  },
  {
    id: 25,
    title: "Cannabis",
    artist: "Ska-P",
    year: 1998,
    subgenre: "Ska Punk",
    ability: "Contraband",
    abilityDesc:
      "Opponent discards one card at random when this card enters play.",
    pop: 62,
    rarity: "Banger",
    country: "Spain",
    artwork: `${ART}artwork.ska-p-cannabis-v1.png`,
  },
];

/** Additional shipped tracks with artwork (catalogue beyond genre fixtures and world sets). */
export const DECK_SPOTLIGHT_CARDS: CardData[] = [
  {
    id: 28,
    title: "Hey Jude",
    artist: "The Beatles",
    year: 1968,
    subgenre: "Pop Rock",
    ability: "Coda",
    abilityDesc: "Draws a second card if popularity is 90 or higher.",
    pop: 95,
    rarity: "Legendary",
    artwork: `${ART}artwork.beatles-v1.png`,
  },
  {
    id: 29,
    title: "God Save the Queen",
    artist: "Sex Pistols",
    year: 1977,
    subgenre: "Metal",
    ability: "Anarchy",
    abilityDesc:
      "Opponent loses 10 popularity when you play a second Rock card this round.",
    pop: 87,
    rarity: "Classic",
    artwork: `${ART}artwork.the-sex-pistols-god-saves-the-queen-v1.png`,
  },
  {
    id: 30,
    title: "The Ketchup Song (Aserejé)",
    artist: "Las Ketchup",
    year: 2002,
    subgenre: "Disco Pop",
    country: "Spain",
    ability: "Choreography",
    abilityDesc: "+8 popularity when played after another dance track.",
    pop: 89,
    rarity: "Banger",
    artwork: `${ART}artwork.las-ketchup-the-ketchup-song-v1.png`,
  },
  {
    id: 31,
    title: "Les Corons",
    artist: "Pierre Bachelet",
    year: 1982,
    subgenre: "French Variety",
    country: "France",
    ability: "Terril",
    abilityDesc:
      "French World cards gain +5 power while this card remains in play.",
    pop: 76,
    rarity: "Classic",
    artwork: `${ART}artwork.les-corons-lens-v1.png`,
  },
  {
    id: 32,
    title: "C'est magnifique",
    artist: "Luis Mariano",
    year: 1951,
    subgenre: "French Variety",
    country: "France",
    ability: "Encore",
    abilityDesc: "Heal 15 HP when played after a Classical or Vintage card.",
    pop: 71,
    rarity: "Classic",
    artwork: `${ART}artwork.luis-mariano-cest-magnifique-v1.png`,
  },
  {
    id: 33,
    title: "Caroline",
    artist: "Zaho feat. MC Solaar",
    year: 2008,
    subgenre: "R&B Soul",
    country: "France",
    ability: "Duettiste",
    abilityDesc:
      "If another French card is on the field, draw one card from the deck.",
    pop: 84,
    rarity: "Banger",
    artwork: `${ART}artwork.zaho-mc-solar-caroline-v1.png`,
  },
];
