import type { CardData } from "@/components/Card";
import type { AppGenreName } from "@/lib/genres";
import { CARD_ARTWORK_PROMPTS } from "./artwork-prompts";
import { ARTWORK_CREATED_AT } from "./artwork-created-at";
import { CARD_ARTWORK_BASE as ART } from "./art-path";

function artworkPromptFor(id: number): { artworkPrompt: string } | undefined {
  const s = CARD_ARTWORK_PROMPTS[id];
  return s ? { artworkPrompt: s } : undefined;
}

/** One fixture card per app genre (charter anatomy, rarity grid). */
export const MOCK_CARDS: Record<AppGenreName, CardData> = {
  Rock: {
    id: 1,
    title: "Bohemian Rhapsody",
    artist: "Queen",
    year: 1975,
    genre: "Pop Rock",
    ability: "Anthemic",
    abilityDesc: "Doubles momentum on any track with a guitar solo.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.bohemian-rhapsody-v2.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.bohemian-rhapsody-v2.png"],
  },
  Mainstream: {
    id: 2,
    title: "Billie Jean",
    artist: "Michael Jackson",
    year: 1982,
    genre: "Disco Pop",
    ability: "Crossover",
    abilityDesc: "Gains +10 popularity when played after a dance track.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.billy-jean-v2.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.billy-jean-v2.png"],
  },
  Electronic: {
    id: 3,
    title: "One More Time",
    artist: "Daft Punk",
    year: 2000,
    genre: "House",
    ability: "Loop Sync",
    abilityDesc: "Repeats its effect once if experimental is above 60.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.daft-punk-one-more-time-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.daft-punk-one-more-time-v1.png"],
    ...(artworkPromptFor(3) ?? {}),
  },
  "Reggae/Dub": {
    id: 4,
    title: "Is This Love",
    artist: "Bob Marley",
    year: 1978,
    genre: "Roots",
    ability: "Roots",
    abilityDesc: "Heals 20 HP when adjacent to a World genre card.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.is-this-love-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.is-this-love-v1.png"],
  },
  "Hip-Hop": {
    id: 5,
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    year: 2017,
    genre: "Trap",
    ability: "Lyrical",
    abilityDesc:
      "Drains 15 power from the opponent when popularity is 7 or higher.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.kendrick-lamar-humble-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.kendrick-lamar-humble-v1.png"],
    ...(artworkPromptFor(5) ?? {}),
  },
  "Disco/Funk": {
    id: 6,
    title: "Night Fever",
    artist: "Bee Gees",
    year: 1977,
    genre: "Disco",
    ability: "Groove",
    abilityDesc: "Boosts all Funk cards on the field by +5 popularity.",
    pop: 9,
    rarity: "Banger",
    artwork: `${ART}artwork.night-fever-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.night-fever-v1.png"],
  },
  Classical: {
    id: 7,
    title: "Ride of the Valkyries",
    artist: "Wagner",
    year: 1876,
    genre: "Soul",
    ability: "Fortissimo",
    abilityDesc: "Deals damage in three separate strikes of 60% power each.",
    pop: 6,
    rarity: "Legendary",
    artwork: `${ART}artwork.wagner-ride-of-the-valkyries-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.wagner-ride-of-the-valkyries-v1.png"],
    ...(artworkPromptFor(7) ?? {}),
  },
  Vintage: {
    id: 8,
    title: "So What",
    artist: "Miles Davis",
    year: 1959,
    genre: "Jazz",
    ability: "Modal",
    abilityDesc: "Random multiplier between ×1 and ×3 on each use.",
    pop: 5,
    rarity: "Classic",
    artwork: `${ART}artwork.miles-davis-so-what-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.miles-davis-so-what-v1.png"],
    ...(artworkPromptFor(8) ?? {}),
  },
};

/** World cards: country/region identity on the type strip (no genre mix). */
export const WORLD_FLAG_CARDS: CardData[] = [
  {
    id: 20,
    title: "Take Me Home, Country Roads",
    artist: "John Denver",
    year: 1971,
    genre: "Country",
    ability: "Heartland",
    abilityDesc: "Restores 10 HP to all allied cards when played.",
    pop: 8,
    rarity: "Banger",
    country: "USA",
    artwork: `${ART}artwork.take-me-home-country-roads-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.take-me-home-country-roads-v1.png"],
  },
  {
    id: 24,
    title: "Les Lacs du Connemara",
    artist: "Michel Sardou",
    year: 1981,
    genre: "French Variety",
    ability: "Melancholy",
    abilityDesc: "Draws 2 cards from the deck when played after a Legendary.",
    pop: 7,
    rarity: "Banger",
    country: "France",
    artwork: `${ART}artwork.michel-sardou-les-lacs-du-connemara-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.michel-sardou-les-lacs-du-connemara-v1.png"],
    ...(artworkPromptFor(24) ?? {}),
  },
  {
    id: 26,
    title: "Tri Martolod",
    artist: "Traditional",
    year: 1972,
    genre: "Folk Breton",
    ability: "Rising Tide",
    abilityDesc: "Gain +10 power for each allied World card in play.",
    pop: 6,
    rarity: "Banger",
    country: "Bretagne",
    artwork: `${ART}artwork.tri-martolod-v1.png`,
    artworkOffsetY: -25,
    artworkOverBorder: true,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.tri-martolod-v1.png"],
    ...(artworkPromptFor(26) ?? {}),
  },
];

/** World + genre/subgenre mixes (fade, dual identity on strip). */
export const WORLD_MIXED_CARDS: CardData[] = [
  {
    id: 27,
    title: "Bande Organisée",
    artist: "13 Organisé",
    year: 2020,
    genre: "Rap",
    ability: "Street Anthem",
    abilityDesc:
      "Allied Hip-Hop cards gain +12 popularity on the turn this card is played.",
    pop: 9,
    rarity: "Classic",
    country: "France",
    artwork: `${ART}artwork.13-organises-bande-organisee-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.13-organises-bande-organisee-v1.png"],
    ...(artworkPromptFor(27) ?? {}),
  },
  {
    id: 21,
    title: "Amazing Grace",
    artist: "Traditional",
    year: 1779,
    genre: "Cantique",
    ability: "Redemption",
    abilityDesc: "Revives one defeated allied card with 30 HP.",
    pop: 7,
    rarity: "Classic",
    country: "USA",
    artwork: `${ART}artwork.amazing-grace-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.amazing-grace-v1.png"],
    ...(artworkPromptFor(21) ?? {}),
  },
  {
    id: 23,
    title: "La Marseillaise",
    artist: "Rouget de Lisle",
    year: 1792,
    genre: "Anthem",
    ability: "Liberty",
    abilityDesc: "Grants +15 power to all allied cards on the next turn.",
    pop: 7,
    rarity: "Legendary",
    country: "France",
    artwork: `${ART}artwork.rouget-de-lisle-la-marseillaise-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.rouget-de-lisle-la-marseillaise-v1.png"],
    ...(artworkPromptFor(23) ?? {}),
  },
  {
    id: 25,
    title: "Cannabis",
    artist: "Ska-P",
    year: 1998,
    genre: "Ska Punk",
    ability: "Contraband",
    abilityDesc:
      "Opponent discards one card at random when this card enters play.",
    pop: 6,
    rarity: "Banger",
    country: "Spain",
    artwork: `${ART}artwork.ska-p-cannabis-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.ska-p-cannabis-v1.png"],
  },
];

/** Additional shipped tracks with artwork (catalogue beyond genre fixtures and world sets). */
export const DECK_SPOTLIGHT_CARDS: CardData[] = [
  {
    id: 28,
    title: "Hey Jude",
    artist: "The Beatles",
    year: 1968,
    genre: "Pop Rock",
    ability: "Coda",
    abilityDesc: "Draws a second card if popularity is 9.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.beatles-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.beatles-v1.png"],
  },
  {
    id: 29,
    title: "God Save the Queen",
    artist: "Sex Pistols",
    year: 1977,
    genre: "Punk",
    ability: "Anarchy",
    abilityDesc:
      "Opponent loses 10 popularity when you play a second Rock card this round.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.the-sex-pistols-god-saves-the-queen-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.the-sex-pistols-god-saves-the-queen-v1.png"],
  },
  {
    id: 30,
    title: "The Ketchup Song (Aserejé)",
    artist: "Las Ketchup",
    year: 2002,
    genre: "Disco Pop",
    country: "Spain",
    ability: "Choreography",
    abilityDesc: "+8 popularity when played after another dance track.",
    pop: 9,
    rarity: "Banger",
    artwork: `${ART}artwork.las-ketchup-the-ketchup-song-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.las-ketchup-the-ketchup-song-v1.png"],
  },
  {
    id: 31,
    title: "Les Corons",
    artist: "Pierre Bachelet",
    year: 1982,
    genre: "French Variety",
    country: "France",
    ability: "Terril",
    abilityDesc:
      "French World cards gain +5 power while this card remains in play.",
    pop: 7,
    rarity: "Classic",
    artwork: `${ART}artwork.les-corons-lens-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.les-corons-lens-v1.png"],
  },
  {
    id: 32,
    title: "C'est magnifique",
    artist: "Luis Mariano",
    year: 1951,
    genre: "French Variety",
    country: "France",
    ability: "Encore",
    abilityDesc: "Heal 15 HP when played after a Classical or Vintage card.",
    pop: 7,
    rarity: "Classic",
    artwork: `${ART}artwork.luis-mariano-cest-magnifique-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.luis-mariano-cest-magnifique-v1.png"],
  },
  {
    id: 33,
    title: "Caroline",
    artist: "Zaho feat. MC Solaar",
    year: 2008,
    genre: "R&B",
    country: "France",
    ability: "Duettiste",
    abilityDesc:
      "If another French card is on the field, draw one card from the deck.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.zaho-mc-solar-caroline-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.zaho-mc-solar-caroline-v1.png"],
  },
  {
    id: 34,
    title: "La Cucaracha",
    artist: "Traditional (Mexico)",
    year: 1880,
    genre: "Mexican Folk",
    country: "Mexico",
    ability: "Reserve",
    abilityDesc: "Planned catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.la-cucaracha-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.la-cucaracha-v1.png"],
  },
  {
    id: 35,
    title: "Abdel Kader",
    artist: "Rachid Taha, Khaled, Faudel",
    year: 1998,
    genre: "Raï",
    country: "Algeria",
    ability: "Caravan",
    abilityDesc:
      "Allied World cards gain +4 popularity when this card enters play.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.un-deux-trois-soleil-abdel-kader-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.un-deux-trois-soleil-abdel-kader-v1.png"],
    ...(artworkPromptFor(35) ?? {}),
  },
  {
    id: 36,
    title: "Despacito",
    artist: "Luis Fonsi feat. Daddy Yankee",
    year: 2017,
    genre: "Reggaeton",
    country: "Puerto Rico",
    ability: "Viral",
    abilityDesc:
      "+10 popularity when played after another World or Mainstream card.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.luiz-fonzi-despacito-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.luiz-fonzi-despacito-v1.png"],
    ...(artworkPromptFor(36) ?? {}),
  },
  {
    id: 37,
    title: "Sky and Sand",
    artist: "Paul Kalkbrenner",
    year: 2008,
    genre: "Minimal",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.paul-karlkbrenner-sky-and-sand-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.paul-karlkbrenner-sky-and-sand-v1.png"],
    ...(artworkPromptFor(37) ?? {}),
  },
  {
    id: 38,
    title: "God Save the King",
    year: 1745,
    genre: "Anthem",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 5,
    rarity: "Banger",
    artwork: `${ART}artwork.god-saves-the-king-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.god-saves-the-king-v1.png"],
    ...(artworkPromptFor(38) ?? {}),
  },
  {
    id: 39,
    title: "God Save the Queen",
    year: 1745,
    genre: "Anthem",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 5,
    rarity: "Banger",
    artwork: `${ART}artwork.god-saves-the-queen-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.god-saves-the-queen-v1.png"],
    ...(artworkPromptFor(39) ?? {}),
  },
  {
    id: 40,
    title: "Au DD",
    artist: "PNL",
    year: 2019,
    genre: "Cloud Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.pnl-au-dd-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.pnl-au-dd-v1.png"],
  },
  {
    id: 41,
    title: "Maria Maria",
    artist: "Santana feat. The Product G&B",
    year: 1999,
    genre: "R&B",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.carlos-santana-maria-maria-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.carlos-santana-maria-maria-v1.png"],
    ...(artworkPromptFor(41) ?? {}),
  },
  {
    id: 42,
    title: "Levels",
    artist: "Avicii",
    year: 2011,
    genre: "EDM",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.avicii-levels-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.avicii-levels-v1.png"],
    ...(artworkPromptFor(42) ?? {}),
  },
  {
    id: 43,
    title: "My Heart Will Go On",
    artist: "Celine Dion",
    year: 1997,
    genre: "Disco Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.celine-dion-my-hearth-will-go-on-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.celine-dion-my-hearth-will-go-on-v1.png"],
  },
  {
    id: 44,
    title: "Lose Yourself",
    artist: "Eminem",
    year: 2002,
    genre: "Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.eminem-loge-yourself-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.eminem-loge-yourself-v1.png"],
    ...(artworkPromptFor(44) ?? {}),
  },
  {
    id: 45,
    title: "Gangnam Style",
    artist: "PSY",
    year: 2012,
    genre: "Electropop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.psy-gagnam-style-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.psy-gagnam-style-v1.png"],
    ...(artworkPromptFor(45) ?? {}),
  },
  {
    id: 46,
    title: "Poker Face",
    artist: "Lady Gaga",
    year: 2008,
    genre: "Dance Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.lady-gaga-poker-face-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.lady-gaga-poker-face-v1.png"],
    ...(artworkPromptFor(46) ?? {}),
  },
  {
    id: 47,
    title: "Thriller",
    artist: "Michael Jackson",
    year: 1982,
    genre: "Disco Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.michael-jackson-thriller-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.michael-jackson-thriller-v1.png"],
    ...(artworkPromptFor(47) ?? {}),
  },
  {
    id: 48,
    title: "Sicko Mode",
    artist: "Travis Scott",
    year: 2018,
    genre: "Cloud Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Classic",
    artwork: `${ART}artwork.sicko-mode-travis-scott-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.sicko-mode-travis-scott-v1.png"],
    ...(artworkPromptFor(48) ?? {}),
  },
  {
    id: 49,
    title: "Shape of You",
    artist: "Ed Sheeran",
    year: 2017,
    genre: "Electropop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.shape-of-you-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.shape-of-you-v1.png"],
  },
  {
    id: 50,
    title: "La Tribu de Dana",
    artist: "Manau",
    year: 1998,
    country: "Bretagne",
    genre: "Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 2,
    rarity: "Banger",
    artwork: `${ART}artwork.danau-latribu-de-dana-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.danau-latribu-de-dana-v1.png"],
    ...(artworkPromptFor(50) ?? {}),
  },
  {
    id: 51,
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    year: 1971,
    genre: "Prog Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.led-zeppelin-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.led-zeppelin-v1.png"],
    ...(artworkPromptFor(51) ?? {}),
  },
  {
    id: 52,
    title: "Bella Ciao",
    year: 1880,
    genre: "Italian Folk",
    country: "Italy",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.bella-ciao-original-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.bella-ciao-original-v1.png"],
    ...(artworkPromptFor(52) ?? {}),
  },
  {
    id: 53,
    title: "Bella Ciao",
    artist: "El Profesor",
    year: 2017,
    genre: "Electropop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.bella-ciao-casa-de-papel-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.bella-ciao-casa-de-papel-v1.png"],
    ...(artworkPromptFor(53) ?? {}),
  },
  {
    id: 54,
    title: "Spring (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1725,
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-spring-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-spring-v1.png"],
    ...(artworkPromptFor(54) ?? {}),
  },
  {
    id: 55,
    title: "Summer (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1725,
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-summer-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-summer-v1.png"],
    ...(artworkPromptFor(55) ?? {}),
  },
  {
    id: 56,
    title: "Autumn (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1725,
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-autumn-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-autumn-v1.png"],
    ...(artworkPromptFor(56) ?? {}),
  },
  {
    id: 57,
    title: "Winter (The Four Seasons)",
    artist: "Antonio Vivaldi",
    year: 1725,
    genre: "Baroque Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Banger",
    artwork: `${ART}artwork.vivaldi-winter-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.vivaldi-winter-v1.png"],
    ...(artworkPromptFor(57) ?? {}),
  },
  {
    id: 58,
    title: "Shake It Off",
    artist: "Taylor Swift",
    year: 2014,
    genre: "Dance Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.taylor-swift-shake-it-off-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.taylor-swift-shake-it-off-v1.png"],
  },
  {
    id: 59,
    title: "Sandstorm",
    artist: "Darude",
    year: 1999,
    genre: "EDM",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.darude-sandstorm-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.darude-sandstorm-v1.png"],
  },
  {
    id: 61,
    title: "These Boots Are Made for Walkin'",
    artist: "Nancy Sinatra",
    year: 1966,
    genre: "Traditional Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.these-boots-are-made-for-walkin-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.these-boots-are-made-for-walkin-v1.png"],
  },
  {
    id: 62,
    title: "These Boots Are Made for Walkin' (alt)",
    artist: "Nancy Sinatra",
    year: 1966,
    genre: "Traditional Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.these-boots-are-made-for-walkin-v2.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.these-boots-are-made-for-walkin-v2.png"],
  },
  {
    id: 63,
    title: "Suck My Kiss",
    artist: "Red Hot Chili Peppers",
    year: 1991,
    genre: "Pop Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.red-hot-chili-peppers-suck-my-kiss-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.red-hot-chili-peppers-suck-my-kiss-v1.png"],
    ...(artworkPromptFor(63) ?? {}),
  },
  {
    id: 64,
    title: "Me Gustas Tú",
    artist: "Manu Chao",
    year: 2001,
    genre: "Roots",
    country: "Spain",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.me-gustas-tu-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.me-gustas-tu-v1.png"],
  },
  {
    id: 65,
    title: "Lacrimosa",
    artist: "Wolfgang Amadeus Mozart",
    year: 1791,
    genre: "Sacred Choral",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.mozart-requiem-lacrimosa-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.mozart-requiem-lacrimosa-v1.png"],
  },
  {
    id: 66,
    title: "Dies Irae",
    artist: "Giuseppe Verdi",
    year: 1874,
    genre: "Romantic Classical",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.verdi-dies-irae-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.verdi-dies-irae-v1.png"],
    ...(artworkPromptFor(66) ?? {}),
  },
  {
    id: 67,
    title: "Cry Me a River",
    artist: "Justin Timberlake",
    year: 2002,
    genre: "R&B",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.justin-timberlake-cry-me-a-river-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.justin-timberlake-cry-me-a-river-v1.png"],
    ...(artworkPromptFor(67) ?? {}),
  },
  {
    id: 68,
    title: "Seven Nation Army",
    artist: "The White Stripes",
    year: 2003,
    genre: "Alternative Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.white-stripes-seven-nation-army-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.white-stripes-seven-nation-army-v1.png"],
    ...(artworkPromptFor(68) ?? {}),
  },
  {
    id: 69,
    title: "Blue (Da Ba Dee)",
    artist: "Eiffel 65",
    year: 1999,
    genre: "Electropop",
    country: "Italy",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.eiffel-65-blue-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.eiffel-65-blue-v1.png"],
    ...(artworkPromptFor(69) ?? {}),
  },
  {
    id: 70,
    title: "Without Me",
    artist: "Eminem",
    year: 2002,
    genre: "Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.without-me-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.without-me-v1.png"],
  },
  {
    id: 71,
    title: "Enter Sandman",
    artist: "Metallica",
    year: 1991,
    genre: "Metal",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.metallica-enter-sandman-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.metallica-enter-sandman-v1.png"],
    ...(artworkPromptFor(71) ?? {}),
  },
  {
    id: 72,
    title: "Symphony No. 5",
    artist: "Ludwig van Beethoven",
    year: 1808,
    genre: "Symphonic Showpiece",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.beethoven-symphony-no-5-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.beethoven-symphony-no-5-v1.png"],
  },
  {
    id: 73,
    title: "O Fortuna",
    artist: "Carl Orff",
    year: 1937,
    genre: "Symphonic Showpiece",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.carmina-burana-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.carmina-burana-v1.png"],
  },
  {
    id: 74,
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    year: 1991,
    genre: "Grunge",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.smells-like-teen-spirit-v2.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.smells-like-teen-spirit-v2.png"],
  },
  {
    id: 75,
    title: "Money",
    artist: "Pink Floyd",
    year: 1973,
    genre: "Prog Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.money-v2.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.money-v2.png"],
  },
  {
    id: 76,
    title: "Take Five",
    artist: "The Golden Gate Quartet",
    year: 1961,
    genre: "Spiritual",
    country: "USA",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Classic",
    artwork: `${ART}artwork.golden-gate-quartet-take-five-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.golden-gate-quartet-take-five-v1.png"],
    ...(artworkPromptFor(76) ?? {}),
  },
  {
    id: 77,
    title: "Bro Gozh ma Zadou",
    artist: "Traditional",
    year: 1897,
    genre: "Folk Breton",
    country: "Bretagne",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 6,
    rarity: "Banger",
    artwork: `${ART}artwork.bro-gozh-ma-zadou-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.bro-gozh-ma-zadou-v1.png"],
    ...(artworkPromptFor(77) ?? {}),
  },
  {
    id: 78,
    title: "Hakuna Matata",
    artist: "The Lion King cast",
    year: 1994,
    genre: "Mainstream",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.hakuna-matata-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.hakuna-matata-v1.png"],
  },
  {
    id: 79,
    title: "California Love",
    artist: "2Pac feat. Dr. Dre",
    year: 1995,
    genre: "Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.dr-dre-tupac-california-love-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.dr-dre-tupac-california-love-v1.png"],
    ...(artworkPromptFor(79) ?? {}),
  },
  {
    id: 80,
    title: "Guerrilla Radio",
    artist: "Rage Against the Machine",
    year: 1999,
    genre: "Pop Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Legendary",
    artwork: `${ART}artwork.ratm-guerilla-radio-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.ratm-guerilla-radio-v1.png"],
  },
  {
    id: 81,
    title: "Shaft",
    artist: "Isaac Hayes",
    year: 1971,
    genre: "Disco",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.isaac-hays-shaft-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.isaac-hays-shaft-v1.png"],
    ...(artworkPromptFor(81) ?? {}),
  },
  {
    id: 82,
    title: "Shaft",
    artist: "Malik Adouane",
    year: 1993,
    genre: "Techno",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 6,
    rarity: "Banger",
    artwork: `${ART}artwork.shaft-malik-adouane-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.shaft-malik-adouane-v1.png"],
    ...(artworkPromptFor(82) ?? {}),
  },
  {
    id: 83,
    title: "Woman to Woman",
    artist: "Joe Cocker",
    year: 1972,
    genre: "Soul Rock",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.joe-cocker-woman-to-woman-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.joe-cocker-woman-to-woman-v1.png"],
  },
  {
    id: 84,
    title: "Opus",
    artist: "Eric Prydz",
    year: 2015,
    genre: "EDM",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.eric-prydz-opus-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.eric-prydz-opus-v1.png"],
  },
  {
    id: 85,
    title: "Opus",
    artist: "Four Tet",
    year: 2016,
    genre: "Progressive House",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.four-tet-opus-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.four-tet-opus-v1.png"],
  },
  {
    id: 86,
    title: "Opus",
    artist: "Lunatic",
    year: 2024,
    genre: "Peak Time Techno",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.lunatic-opus-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.lunatic-opus-v1.png"],
  },
  {
    id: 87,
    title: "Africa",
    artist: "Toto",
    year: 1982,
    genre: "Pop Rock",
    ability: "Savanna stack",
    abilityDesc:
      "Reads as pop on the strip but smuggles hardcore weight: massed percussion, marimba layers, and session-musician polyphony under an immovable chorus.",
    pop: 9,
    rarity: "Classic",
    artwork: `${ART}artwork.toto-africa-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.toto-africa-v1.png"],
    ...(artworkPromptFor(87) ?? {}),
  },
  {
    id: 88,
    title: "The Next Episode",
    artist: "Dr. Dre feat. Snoop Dogg",
    year: 1999,
    genre: "Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "Legendary",
    artwork: `${ART}artwork.dr-dre-next-episode-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.dr-dre-next-episode-v1.png"],
  },
  {
    id: 89,
    title: "The Edge",
    artist: "David McCallum",
    year: 1968,
    genre: "Jazz",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    artwork: `${ART}artwork.david-mccallum-the-edge-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.david-mccallum-the-edge-v1.png"],
    artworkOffsetY: -20,
  },
];
