import type { CatalogSeriesType } from "@/lib/card-theme-types";

/**
 * Shipped-deck catalogue № and series bucket per card id.
 * Source of truth for numbering; {@link lib/cards/catalog.ts} reads these only.
 * Regenerate with: npx tsx scripts/generate-shipped-catalog-meta.mts
 */
export const SHIPPED_CATALOG_META_BY_ID: Record<
  number,
  {
    catalogNumber: number;
    catalogSeriesType: CatalogSeriesType;
    catalogSeriesLabel: string;
  }
> = {
  1: { catalogNumber: 1, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  2: { catalogNumber: 1, catalogSeriesType: "genre", catalogSeriesLabel: "Disco/Funk" },
  3: { catalogNumber: 1, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  4: { catalogNumber: 1, catalogSeriesType: "genre", catalogSeriesLabel: "Reggae/Dub" },
  5: { catalogNumber: 1, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  6: { catalogNumber: 2, catalogSeriesType: "genre", catalogSeriesLabel: "Disco/Funk" },
  7: { catalogNumber: 1, catalogSeriesType: "genre", catalogSeriesLabel: "Vintage" },
  8: { catalogNumber: 2, catalogSeriesType: "genre", catalogSeriesLabel: "Vintage" },
  20: { catalogNumber: 1, catalogSeriesType: "country", catalogSeriesLabel: "USA" },
  21: { catalogNumber: 3, catalogSeriesType: "genre", catalogSeriesLabel: "Vintage" },
  23: { catalogNumber: 1, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  24: { catalogNumber: 1, catalogSeriesType: "country", catalogSeriesLabel: "France" },
  25: { catalogNumber: 2, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  26: { catalogNumber: 1, catalogSeriesType: "country", catalogSeriesLabel: "Bretagne" },
  27: { catalogNumber: 2, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  28: { catalogNumber: 3, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  29: { catalogNumber: 4, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  30: { catalogNumber: 3, catalogSeriesType: "genre", catalogSeriesLabel: "Disco/Funk" },
  31: { catalogNumber: 2, catalogSeriesType: "country", catalogSeriesLabel: "France" },
  32: { catalogNumber: 3, catalogSeriesType: "country", catalogSeriesLabel: "France" },
  33: { catalogNumber: 3, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  34: { catalogNumber: 1, catalogSeriesType: "country", catalogSeriesLabel: "Mexico" },
  35: { catalogNumber: 1, catalogSeriesType: "country", catalogSeriesLabel: "Algeria" },
  36: { catalogNumber: 1, catalogSeriesType: "country", catalogSeriesLabel: "Puerto Rico" },
  37: { catalogNumber: 2, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  38: { catalogNumber: 2, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  39: { catalogNumber: 3, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  40: { catalogNumber: 4, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  41: { catalogNumber: 5, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  42: { catalogNumber: 3, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  43: { catalogNumber: 4, catalogSeriesType: "genre", catalogSeriesLabel: "Disco/Funk" },
  44: { catalogNumber: 6, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  45: { catalogNumber: 4, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  46: { catalogNumber: 5, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  47: { catalogNumber: 5, catalogSeriesType: "genre", catalogSeriesLabel: "Disco/Funk" },
  48: { catalogNumber: 7, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  49: { catalogNumber: 6, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  50: { catalogNumber: 8, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  51: { catalogNumber: 5, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  52: { catalogNumber: 1, catalogSeriesType: "country", catalogSeriesLabel: "Italy" },
  53: { catalogNumber: 7, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  54: { catalogNumber: 4, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  55: { catalogNumber: 5, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  56: { catalogNumber: 6, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  57: { catalogNumber: 7, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  58: { catalogNumber: 8, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  59: { catalogNumber: 9, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  61: { catalogNumber: 4, catalogSeriesType: "genre", catalogSeriesLabel: "Vintage" },
  62: { catalogNumber: 5, catalogSeriesType: "genre", catalogSeriesLabel: "Vintage" },
  63: { catalogNumber: 6, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  64: { catalogNumber: 2, catalogSeriesType: "genre", catalogSeriesLabel: "Reggae/Dub" },
  65: { catalogNumber: 8, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  66: { catalogNumber: 9, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  67: { catalogNumber: 9, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  68: { catalogNumber: 7, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  69: { catalogNumber: 10, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  70: { catalogNumber: 10, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  71: { catalogNumber: 8, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  72: { catalogNumber: 10, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  73: { catalogNumber: 11, catalogSeriesType: "genre", catalogSeriesLabel: "Classical" },
  74: { catalogNumber: 9, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  75: { catalogNumber: 10, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  76: { catalogNumber: 2, catalogSeriesType: "country", catalogSeriesLabel: "USA" },
  77: { catalogNumber: 2, catalogSeriesType: "country", catalogSeriesLabel: "Bretagne" },
  78: { catalogNumber: 1, catalogSeriesType: "genre", catalogSeriesLabel: "Pop" },
  79: { catalogNumber: 11, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  80: { catalogNumber: 11, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  81: { catalogNumber: 6, catalogSeriesType: "genre", catalogSeriesLabel: "Disco/Funk" },
  82: { catalogNumber: 11, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  83: { catalogNumber: 12, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  84: { catalogNumber: 12, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  85: { catalogNumber: 13, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  86: { catalogNumber: 14, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  87: { catalogNumber: 13, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  88: { catalogNumber: 12, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  89: { catalogNumber: 6, catalogSeriesType: "genre", catalogSeriesLabel: "Vintage" },
  90: { catalogNumber: 15, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  91: { catalogNumber: 7, catalogSeriesType: "genre", catalogSeriesLabel: "Disco/Funk" },
  92: { catalogNumber: 14, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  93: { catalogNumber: 16, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
  94: { catalogNumber: 13, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  95: { catalogNumber: 15, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  96: { catalogNumber: 14, catalogSeriesType: "genre", catalogSeriesLabel: "Hip-Hop" },
  97: { catalogNumber: 1, catalogSeriesType: "country", catalogSeriesLabel: "Switzerland" },
  98: { catalogNumber: 1, catalogSeriesType: "country", catalogSeriesLabel: "Russia" },
  99: { catalogNumber: 2, catalogSeriesType: "country", catalogSeriesLabel: "Russia" },
  100: { catalogNumber: 7, catalogSeriesType: "genre", catalogSeriesLabel: "Vintage" },
  101: { catalogNumber: 2, catalogSeriesType: "genre", catalogSeriesLabel: "Pop" },
  102: { catalogNumber: 16, catalogSeriesType: "genre", catalogSeriesLabel: "Rock" },
  103: { catalogNumber: 8, catalogSeriesType: "genre", catalogSeriesLabel: "Vintage" },
  104: { catalogNumber: 3, catalogSeriesType: "genre", catalogSeriesLabel: "Reggae/Dub" },
  9101: { catalogNumber: 17, catalogSeriesType: "genre", catalogSeriesLabel: "Electronic" },
};
