import type { CardData } from "@/components/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const VINTAGE_CARDS: CardData[] = [
  {
    catalogNumber: 18,
    id: 114,
    songsOut: [115],
    title: "Amen, Brother",
    artist: "The Winstons",
    year: "1969",
    genre: "Early Funk",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "LEGENDARY",
    artwork: `${ART}artwork.the-winstons-amen-brother-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.the-winstons-amen-brother-v1.png"],
    ...(artworkPromptFor(114) ?? {}),
  },
  {
    catalogNumber: 2,
    id: 8,
    title: "So What",
    artist: "",
    year: "1959",
    genre: "Jazz",
    ability: "Modal",
    abilityDesc: "Random multiplier between ×1 and ×3 on each use.",
    pop: 5,
    rarity: "CLASSIC",
    artwork: `${ART}artwork.miles-davis-so-what-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.miles-davis-so-what-v1.png"],
    ...(artworkPromptFor(8) ?? {}),
  },
  {
    catalogNumber: 4,
    id: 61,
    title: "These Boots Are Made for Walkin'",
    artist: "Nancy Sinatra",
    year: "1966",
    genre: "Traditional Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "CLASSIC",
    artwork: `${ART}artwork.these-boots-are-made-for-walkin-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.these-boots-are-made-for-walkin-v1.png"],
  },
  {
    catalogNumber: 5,
    id: 53,
    title: "Bella Ciao",
    artist: "",
    year: "2017",
    genre: "Choral",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "BANGER",
    artwork: `${ART}artwork.bella-ciao-casa-de-papel-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.bella-ciao-casa-de-papel-v1.png"],
    ...(artworkPromptFor(53) ?? {}),
  },
  {
    catalogNumber: 6,
    id: 89,
    title: "The Edge",
    artist: "",
    year: "1968",
    genre: "Jazz",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "CLASSIC",
    artwork: `${ART}artwork.david-mccallum-the-edge-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.david-mccallum-the-edge-v1.png"],
    artworkOffsetY: -20,
  },
] as CardData[];
