import type { CardData } from "@/components/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const BRETAGNE_CARDS: CardData[] = [
  {
    catalogNumber: 1,
    id: 26,
    title: "Tri Martolod",
    artist: "Traditional",
    year: 1972,
    genre: "Folk Breton",
    ability: "Rising Tide",
    abilityDesc: "Gain +10 power for each allied World card in play.",
    pop: 6,
    rarity: "Banger",
    country: "Bretagne",
    artwork: `${ART}artwork.tri-martolod-v1.png`,
    artworkOffsetY: -25,
    artworkOverBorder: true,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.tri-martolod-v1.png"],
    ...(artworkPromptFor(26) ?? {}),
  },
  {
    id: 50,
    title: "La Tribu de Dana",
    artist: "Manau",
    year: 1998,
    country: "Bretagne",
    genre: "Rap",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 2,
    rarity: "Banger",
    artwork: `${ART}artwork.danau-latribu-de-dana-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.danau-latribu-de-dana-v1.png"],
    ...(artworkPromptFor(50) ?? {}),
    catalogNumber: 8,
  },
  {
    id: 77,
    title: "Bro Gozh ma Zadou",
    artist: "Traditional",
    year: 1897,
    genre: "Folk Breton",
    country: "Bretagne",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 6,
    rarity: "Banger",
    artwork: `${ART}artwork.bro-gozh-ma-zadou-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.bro-gozh-ma-zadou-v1.png"],
    ...(artworkPromptFor(77) ?? {}),
    catalogNumber: 2,
  },
];
