import type { CardData } from "@/components/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const FRANCE_CARDS: CardData[] = [
  {
    id: 23,
    title: "La Marseillaise",
    artist: "Rouget de Lisle",
    year: 1792,
    genre: "Anthem",
    ability: "Liberty",
    abilityDesc: "Grants +15 power to all allied cards on the next turn.",
    pop: 7,
    rarity: "Legendary",
    country: "France",
    artwork: `${ART}artwork.rouget-de-lisle-la-marseillaise-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.rouget-de-lisle-la-marseillaise-v1.png"],
    ...(artworkPromptFor(23) ?? {}),
    catalogNumber: 1,
  },
  {
    id: 24,
    title: "Les Lacs du Connemara",
    artist: "Michel Sardou",
    year: 1981,
    genre: "French Variety",
    ability: "Melancholy",
    abilityDesc: "Draws 2 cards from the deck when played after a Legendary.",
    pop: 7,
    rarity: "Banger",
    country: "France",
    artwork: `${ART}artwork.michel-sardou-les-lacs-du-connemara-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.michel-sardou-les-lacs-du-connemara-v1.png"],
    ...(artworkPromptFor(24) ?? {}),
    catalogNumber: 1,
  },
  {
    id: 27,
    title: "Bande Organisée",
    artist: "13 Organisé",
    year: 2020,
    genre: "Rap",
    ability: "Street Anthem",
    abilityDesc:
      "Allied Hip-Hop cards gain +12 popularity on the turn this card is played.",
    pop: 9,
    rarity: "Classic",
    country: "France",
    artwork: `${ART}artwork.13-organises-bande-organisee-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.13-organises-bande-organisee-v1.png"],
    ...(artworkPromptFor(27) ?? {}),
    catalogNumber: 2,
  },
  {
    id: 31,
    title: "Les Corons",
    artist: "Pierre Bachelet",
    year: 1982,
    genre: "French Variety",
    country: "France",
    ability: "Terril",
    artworkOffsetY: -35,
    abilityDesc:
      "French World cards gain +5 power while this card remains in play.",
    pop: 7,
    rarity: "Classic",
    artwork: `${ART}artwork.les-corons-lens-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.les-corons-lens-v1.png"],
    catalogNumber: 2,
  },
  {
    id: 32,
    title: "C'est magnifique",
    artist: "Luis Mariano",
    year: 1951,
    genre: "French Variety",
    country: "France",
    ability: "Encore",
    abilityDesc: "Heal 15 HP when played after a Classical or Vintage card.",
    pop: 7,
    rarity: "Classic",
    artwork: `${ART}artwork.luis-mariano-cest-magnifique-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.luis-mariano-cest-magnifique-v1.png"],
    catalogNumber: 3,
  },
  {
    id: 33,
    title: "Caroline",
    artist: "Zaho feat. MC Solaar",
    year: 2008,
    genre: "R&B",
    country: "France",
    ability: "Duettiste",
    abilityDesc:
      "If another French card is on the field, draw one card from the deck.",
    pop: 8,
    rarity: "Banger",
    artwork: `${ART}artwork.zaho-mc-solar-caroline-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.zaho-mc-solar-caroline-v1.png"],
    catalogNumber: 3,
  },
  {
    id: 103,
    title: "Vois sur ton chemin",
    artist: "Les Choristes",
    year: 2004,
    genre: "Choral",
    country: "France",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "Classic",
    tracksOut: [90],
    artwork: `${ART}artwork.les-choristes-vois-sur-ton-chemin-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.les-choristes-vois-sur-ton-chemin-v1.png"],
    catalogNumber: 8,
  },
];
