import type { CardData } from "@/components/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const USA_CARDS: CardData[] = [
  {
    id: 20,
    title: "Take Me Home, Country Roads",
    artist: "John Denver",
    year: 1971,
    genre: "Country",
    ability: "Heartland",
    abilityDesc: "Restores 10 HP to all allied cards when played.",
    pop: 8,
    rarity: "Banger",
    country: "USA",
    artwork: `${ART}artwork.take-me-home-country-roads-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.take-me-home-country-roads-v1.png"],
    catalogNumber: 1,
    catalogSeriesLabel: "USA",
  },
  {
    id: 21,
    title: "Amazing Grace",
    artist: "Traditional",
    year: 1779,
    genre: "Cantique",
    ability: "Redemption",
    abilityDesc: "Revives one defeated allied card with 30 HP.",
    pop: 7,
    rarity: "Classic",
    country: "USA",
    artwork: `${ART}artwork.amazing-grace-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["artwork.amazing-grace-v1.png"],
    ...(artworkPromptFor(21) ?? {}),
    catalogNumber: 3,
    catalogSeriesLabel: "Vintage",
  },
  {
    id: 76,
    title: "Take Five",
    artist: "The Golden Gate Quartet",
    year: 1961,
    genre: "Spiritual",
    country: "USA",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 7,
    rarity: "Classic",
    artwork: `${ART}artwork.golden-gate-quartet-take-five-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.golden-gate-quartet-take-five-v1.png"],
    ...(artworkPromptFor(76) ?? {}),
    catalogNumber: 2,
    catalogSeriesLabel: "USA",
  },
  {
    id: 100,
    title: "The Great Pretender",
    artist: "The Platters",
    year: 1955,
    genre: "Doo-wop",
    country: "USA",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    tracksOut: [101],
    pop: 9,
    rarity: "Classic",
    artwork: `${ART}artwork.the-platters-the-great-pretender-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["artwork.the-platters-the-great-pretender-v1.png"],
    ...(artworkPromptFor(100) ?? {}),
    catalogNumber: 7,
    catalogSeriesLabel: "Vintage",
  },
];
